### ISSUE TITLE
emit-llvm error for multiple source files

### ISSUE THREAD

**Issue by hongxuchen** [travitch/whole-program-llvm#10]
AFAIK, wllvm calles `$LLVM_COMPILER` to do regular compilation and the `-emit-llvm` compilation. But there are several source files and they are compiled and linked within one compiler(clang/gcc) command(actually the **driver**), then the build for bitcode version would fail. Here is an example:

The original command:

``` shell
$(CC) main.c min.c -o min.out
```

The actual version:

``` shell
clang main.c min.c -o min.out
clang -emit-llvm main.c min.c -c -o .min.out.bc  # error here
```

Compilation would fail for the 2nd line.

In this case, I suppose that the internal wrapper should be separated into 2 steps:  
1. the compilation from source code to object
2. the llvm-link procedure

**Comment by contr4l** [comment]
Sorry to bother, after read this issue, I still do not know how to compile multi source file to one bitcode file. When I try the wllvm -emit-llvm a.c b.c -c -o res.bc, it failed with "clang-7: error: cannot specify -o when generating multiple output files".
What's wrong with my command? 
I also wonder if there is any other solution?

**Comment by ianamason** [comment]
To compile:
```
wllvm foo.c -o foo
```
To get the bitcode:
```
extract-bc foo
```
