### ISSUE TITLE
Could not find ".llvm_bc" ELF section

### ISSUE THREAD

**Issue by Mohannadcse** [travitch/whole-program-llvm#101]
I've created a docker-machine and installed wllvm and LLVM 6.0. I've changed all required flags because the `clang` is installed as `clang-6.0`. However, I still receive that error `Could not find ".llvm_bc" ELF section` when I execute the command `extract-bc`. I'm not quite sure if I'm missing anything
Here is the configuration of the docker image inside the Dockerfile

``` 
# Pull base image.
FROM buildpack-deps:bionic

RUN echo "Build type set to: Release" && \
     # Install deps.
    apt-get update && \
    apt-get install -yqq software-properties-common && \
    apt-get update && \
    apt-get install -y wget libprotobuf-dev python-protobuf protobuf-compiler && \
    apt-get install -y python-pip && \
    apt-get install -y python3-pip && \
    #apt-get install -y z3 && \
    apt-get install -y libz3-dev && \
    apt-get install -y llvm-6.0-dev && \
    apt-get install llvm-6.0-tool && \
    apt-get install -y clang-6.0 && \
    apt-get install -y git && \
    apt-get install -y cmake && \
    apt-get install -y zlib1g-dev && \
    apt-get install -y build-essential &&\
    apt-get install -y gperf  libgoogle-perftools-dev && \
    apt-get install -yqq libboost-dev 

RUN echo "Install WLLVM" && \
    pip3 install -U lit tabulate wllvm

RUN echo "Download google tests" && \
    curl -OL https://github.com/google/googletest/archive/release-1.7.0.zip && \
    unzip release-1.7.0.zip && \
    rm release-1.7.0.zip

RUN echo "Install klee-uclibc" && \
    git clone https://github.com/klee/klee-uclibc.git && \
    cd klee-uclibc && \
    ./configure --make-llvm-lib --with-llvm-config=/usr/bin/llvm-config-6.0 && \
    make -j2

ADD debloat KLEE

WORKDIR build/KLEE

RUN echo "Buildg KLEE" && \ 
    cmake   \
        -DENABLE_SOLVER_Z3=ON  \ 
        -DENABLE_POSIX_RUNTIME=ON  \ 
        -DENABLE_KLEE_UCLIBC=ON   \
        -DKLEE_UCLIBC_PATH=/klee-uclibc \ 
        -DENABLE_UNIT_TESTS=ON \
        -DGTEST_SRC_DIR=../../googletest-release-1.7.0  \
        -DLLVM_CONFIG_BINARY=/usr/bin/llvm-config-6.0 \  
        -DLLVMCC=/usr/bin/clang-6.0  \
        -DLLVMCXX=/usr/bin/clang++-6.0   \
        /KLEE  && \
    make && \
    make install 

ENV LLVM_CC_NAME clang-6.0
ENV LLVM_CXX_NAME clang++-6.0
ENV LLVM_LINK_NAME llvm-link-6.0
ENV LLVM_AR_NAME llvm-ar-6.0
ENV LLVM_COMPILER clang
```

**Comment by ianamason** [comment]
`extract-bc` on what?

where are you compiling with `wllvm` or `wllvm++`?

**Comment by Mohannadcse** [comment]
I already have a set of executable files `from coreutils` that were generated using wllvm on another machine, using the same LLVM version `6.0`. So I copied them to the docker-machine.

**Comment by ianamason** [comment]
Why don't you build something on one machine and extract the bitcode on that same machine.
I'm not going to debug a convoluted workflow like that. Sorry.

**Comment by Mohannadcse** [comment]
I understand. 
I'll do what you suggested and let you know.

**Comment by Mohannadcse** [comment]
Apparently, I need to do everything on the docker machine. My point of exporting binaries, then later on extract the bitcode in the docker is to save time that will be used for building the binaries. Anyway, seems this is inevitable

**Comment by ianamason** [comment]
@Mohannadcse  the binaries do not contain the bitcode. They only contain the (absolute) paths to the bitcode.
You move the binaries, but leave the bitcode behind...

**Comment by ianamason** [comment]
P.S. If you want to save time use gllvm, not wllvm.
