### ISSUE TITLE
How to disable inline in wllvm?

### ISSUE THREAD

**Issue by younaman** [travitch/whole-program-llvm#102]
Hello everyone. I am a green hand. I want to get some inline functions' name in IR.If I generate IR like:
'make CC=wllvm LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump OBJSIZE=llvm-size READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld -j 6'
Some inline functions sach as atomic_inc_return will be inline and it has no name like"atomic_xxx",HOW TO DISABLE INLINE when I use wllvm?thanks!

**Comment by ianamason** [comment]
I am not really sure I know what you are asking. But if you want control over the IR that gets produced. First
see if you can control it using just clang, and additional switches combined with `-emit-llvm`.

Then perhaps you should use the `LLVM_BITCODE_GENERATION_FLAGS` switch to `wllvm`, or preferably `gllvm`.

**Comment by younaman** [comment]
@ianamason Thanks a lot! I have solve the problem.I use opt --no-inlining for every bc in different kernel directories, and link it manually.After that, the total vmlinux.bc is uninlined and I can get all different inline function names!

**Comment by peach-byte** [comment]
> @ianamason Thanks a lot! I have solve the problem.I use opt --no-inlining for every bc in different kernel directories, and link it manually.After that, the total vmlinux.bc is uninlined and I can get all different inline function names!

hello, 
can you please say more about this? you only run `opt --no-inlining ` in each directory?
how did you link them all manually?
