### ISSUE TITLE
generate bitcode for libgd

### ISSUE THREAD

**Issue by peach-byte** [travitch/whole-program-llvm#106]
hello,
I want to use this tool for generating bitcode for [libgd](https://github.com/libgd/libgd).
my llvm version in 10.
```
$ls -l /usr/bin/clang
lrwxrwxrwx 1 root root 17 Mar 27 04:16 /usr/bin/clang -> /usr/bin/clang-10
```
and I used these commands:
```
git clone https://github.com/libgd/libgd.git
cd libgd
export LLVM_COMPILER=clang
CC=wllvm ./configure
make
cd src
extract-bc gd2togif
```
```
ERROR:File "/libgd/src/gd2togif" of type UNKNOWN cannot be used
```

can you please help me?

**Comment by travitch** [comment]
If you just run make and look at those intermediate results,`gd2togif` is a shell script. Look at the executables, or try running install to get libtool to finish processing everything.

**Comment by peach-byte** [comment]
Thank you,
yes, executables are in src/.libs
I try this but again there is a problem!
```
.libs$ extract-bc gd2togif
```
```
ERROR:WLLVM Failed to execute: ['llvm-link',
 '-o=/libgd/src/.libs/gd2togif.bc',
 '/libgd/src/.gd2togif.o.bc']
ERROR:Your llvm-link does not seem to be easy to find.
Either install it or use the -l llvmLinker option.
```

**Comment by travitch** [comment]
`extract-bc` needs access to the `llvm-link` command in order to combine bitcode. If it is not in your `PATH`, you need to pass `extract-bc` the `-l` argument to tell it where to find your copy of `llvm-link` (possibly suffixed with a version number)

**Comment by peach-byte** [comment]
what is the difference between using `./configure; make;` and using cmake for generating executable files for this project?
why generated .bc files are different?
I used these commands to generate

```
export LLVM_COMPILER=clang

mkdir bld
cd bld
CC=wllvm CXX=wllvm++ cmake ../
make

extract-bc Bin/libgd.so.3.0.10
```

```
export LLVM_COMPILER=clang

CC=wllvm ./configure
make

extract-bc src/.libs/libgd.so.3.0.10
```
Thank you
