### ISSUE TITLE
objdump *.cpp.o file format not recognized when use extract-bc to my static library file.

### ISSUE THREAD

**Issue by wuxiaoqiang12** [travitch/whole-program-llvm#108]
My static library file(libddf.a) is generated by link several `*.cpp.o` files.  I use `wllvm` and `wllvm++` to compile my project.
```shell
➜  bin extract-bc libddf.a
objdump: ddf.cpp.o: file format not recognized
ERROR:Could not dump b'ddf.cpp.o'
```
I use `llvm-ar x libddf.a` can see all `.cpp.o` file included in `libddf.a` file. using command `file foo.cpp.o` which said this is an LLVM IR bitcode. also which can be transfer to `.ll` file. I want to know how to transfer `libddf.a` to human readable `.ll` file.

**Comment by ianamason** [comment]
If `foo.cpp.o` is LLVM bitcode, then it sounds like the project is being built with `-lto` in which case using `wllvm` and `wllvm++` is probably not going to help. You should probably just use clang and hunt around for the build products.

Sorry.

**Comment by wuxiaoqiang12** [comment]
I didn't use `-lto` to build my project. My procedure is following:
```shell
Building CXX object pathdir/foo1.cpp.o
cd path/to/foo1 && /usr/local/bin/wllvm++  -I/dependences/header/directory  -g   -std=c++11 -O0 -Wall -Werror -w -emit-llvm -o pathto/foo1.cpp.o -c pathto/foo1.cpp
Building CXX object pathdir/foo2.cpp.o
cd path/to/foo2 && /usr/local/bin/wllvm++  -I/dependences/header/directory  -g   -std=c++11 -O0 -Wall -Werror -w -emit-llvm -o pathto/foo2.cpp.o -c pathto/foo2.cpp
cd path/to/ddf && /usr/local/bin/wllvm++  -I/dependences/header/directory  -g   -std=c++11 -O0 -Wall -Werror -w -emit-llvm -o pathto/ddf.cpp.o -c pathto/ddf.cpp
```
There ddf.cpp include a main function that is my entry point to do dataflow analysis. After build all foo*.cpp.o file, using `ar` command to build libddf.a file:
```shell
Linking CXX static library ../bin/libddf.a
/path/to/binutils-2.36.1/build/binutils/ar qc ../bin/libddf.a  foo1.cpp.o foo2.cpp.o foo3.cpp.o
/path/to/binutils-2.36.1/build/binutils/ranlib ../bin/libddf.a
```
As you can see there is no `-lto` used.
```shell
➜  bin file libddf.a
libddf.a: current ar archive
```
`extract-bc libddf.a` generate:
```shell
➜  bin extract-bc libddf.a
objdump: ddf.cpp.o: file format not recognized
ERROR:Could not dump b'ddf.cpp.o'
```
Using `ar -x libddf.a`
```shell
➜  bin ls
ddf.cpp.o   libddf.a foo1.cpp.o foo2.cpp.o
➜  bin file ddf.cpp.o
ddf.cpp.o: LLVM IR bitcode
➜  bin file foo.cpp.o
ex.cpp.o: LLVM IR bitcode
```
I don't know why I can't use extract-bc to libddf.a.  But I think it it doesn't matter. Maybe I can just analysis ddf.cpp.o file instead of libddf.a. Anyway thanks a lot.

**Comment by ianamason** [comment]
Why are you doing this?
```

cd path/to/foo2 && /usr/local/bin/wllvm++  -I/dependences/header/directory  -g   -std=c++11 -O0 -Wall -Werror -w -emit-llvm -o pathto/foo2.cpp.o -c pathto/foo2.cpp
cd path/to/ddf && /usr/local/bin/wllvm++  -I/dependences/header/directory  -g   -std=c++11 -O0 -Wall -Werror -w -emit-llvm -o pathto/ddf.cpp.o -c pathto/ddf.cpp
```
The `-emit-llvm` is what is making the output be bitcode. I think you have misunderstood how to use wllvm.

You make a project using clang and whatever that builds a normal library. No bitcode anywhere.
Say
```
make
```
builds your library.
Then you do 
```
CC=wllvm CXX=wllvm++ make
```
and then use extract-bc.

**Comment by wuxiaoqiang12** [comment]
Oh, yes. Sorry I misunderstood how to use wllvm. I eliminate the `-emit-llvm` arg. Now I get following:
```shell
➜  bin file libddf.a
libddf.a: current ar archive
➜  bin extract-bc libddf.a
Writing output to /pathto/libddf.bca
llvm-ar: warning: creating /pathto/libddf.bca
Generated LLVM bitcode archive /pathto/libddf.bca
➜  bin ls
libddf.a  libddf.bca  README.md
➜  bin file libddf.bca
libddf.bca: current ar archive
```
You can see after `extract-bc libddf.a` the generated file libddf.bca is still an ar archive instead of llvm ir bitcode.
So I use `llvm-ar x libddf.bca` to extract all llvm bitcode `bc` file. 
```shell
➜  bin llvm-ar x libSTATIC.bca
➜  bin file .ddf.cpp.o.bc
.ddf.cpp.o.bc: LLVM IR bitcode
```
I don't know what's the different between `-emit-llvm` and this way. Or is it just different in executable file not in static library filee? I will see how to build my code to executable file instead of static library. Thank you very much!

**Comment by ianamason** [comment]
If you want a llvm module at the end use the `--bitcode` or `-b`  switch to `extract-bc`.

You usually use wllvm or gllvm on a project someone else has written, with a build system that you do not want to modify.

**Comment by wuxiaoqiang12** [comment]
Ok, thank you very much. You really make my life easyer.
