### ISSUE TITLE
LLVM gold plugin

### ISSUE THREAD

**Issue by peach-byte** [travitch/whole-program-llvm#110]
hello,
Can you please help me to find the differences between your `wllvm` tool and the things this llvm gold plugin do?

I follow the commands from [this](http://gbalats.github.io/2015/12/10/compiling-autotooled-projects-to-LLVM-bitcode.html) page and then I couldn't compare them with re result of your tool.
are they both do the same things?

Thank you.

**Comment by ianamason** [comment]
I can't help sorry. I notice that link is to a blog from 5 years ago.
I do not know anything about the state of the gold plugin.
Sorry.
