### ISSUE TITLE
Invalid syntax error in compilers.py when installing (pip 20.3.4, python 3.5)

### ISSUE THREAD

**Issue by MarwanNour** [travitch/whole-program-llvm#111]
Hello, I am trying to install wllvm on Ubuntu 16.04 using python 3.5 and pip 20.3.4. I have tried installing from source and from pip package and I am getting the following error:
![image](https://user-images.githubusercontent.com/38836519/115544623-1d4ebb00-a2a3-11eb-8880-d864a7d0da10.png)

However installing it with pip 20.3.4 for python 2.7 seems to work.

**Comment by ianamason** [comment]
You need at least python 3.6 as it says in the [setup.py](https://github.com/travitch/whole-program-llvm/blob/master/setup.py)

Not sure why pip went ahead and installed it.

**Comment by ianamason** [comment]
FYI the reason why we require 3.6 is because it uses the new format strings. Amazing that it took
python so long to get string formatting right.

**Comment by MarwanNour** [comment]
Alright thank you for the clarification.

**Comment by ianamason** [comment]
Good question.
