### ISSUE TITLE
build FFmpeg with LLVm 12

### ISSUE THREAD

**Issue by meweez** [travitch/whole-program-llvm#112]
Hello, 
I am using Clang 12 on my macOS:
```
clang --version
clang version 12.0.0
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

I need to use your project on [FFmpeg](https://github.com/FFmpeg/FFmpeg) so I used these commands:
```
brew install automake fdk-aac git lame libass libtool libvorbis libvpx  opus sdl shtool texi2html theora wget x264 x265 xvid nasm
export LLVM_COMPILER=clang
export LLVM_BITCODE_GENERATION_FLAGS='-g'
mkdir build
cd build
CC=wllvm CXX=wllvm++ /Users/macbook/Documents/github-repos/FFmpeg/configure  --prefix=/usr/local --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame  --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libopus --enable-libxvid --samples=fate-suite/

extract-bc ffmpeg
```
but it shows this:
```
ERROR:FFmpeg/build/ffmpeg contained no __WLLVM segment
```
Can you please help me?
Thank you

**Comment by me22bee** [comment]
> Hello,
> I am using Clang 12 on my macOS:
> 
> ```
> clang --version
> clang version 12.0.0
> Target: x86_64-apple-darwin19.6.0
> Thread model: posix
> InstalledDir: /usr/local/opt/llvm/bin
> ```
> 
> I need to use your project on [FFmpeg](https://github.com/FFmpeg/FFmpeg) so I used these commands:
> 
> ```
> brew install automake fdk-aac git lame libass libtool libvorbis libvpx  opus sdl shtool texi2html theora wget x264 x265 xvid nasm
> export LLVM_COMPILER=clang
> export LLVM_BITCODE_GENERATION_FLAGS='-g'
> mkdir build
> cd build
> CC=wllvm CXX=wllvm++ /Users/macbook/Documents/github-repos/FFmpeg/configure  --prefix=/usr/local --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame  --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libopus --enable-libxvid --samples=fate-suite/
> 
> extract-bc ffmpeg
> ```
> 
> but it shows this:
> 
> ```
> ERROR:FFmpeg/build/ffmpeg contained no __WLLVM segment
> ```
> 
> Can you please help me?
> Thank you


I also test it on debian with clang 10 based on this [CompilationGuide](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#FFmpeg): 
```
export CC=wllvm

export LLVM_COMPILER=clang

export LLVM_BITCODE_GENERATION_FLAGS='-g'


  PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig"   ./configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --ld="g++" \
  --bindir="$HOME/bin" \
  --enable-gpl \
  --enable-gnutls \
  --enable-libaom \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree 

PATH="$HOME/bin:$PATH" make
extract-bc ffmpeg
```

```
WARNING:Could not find ".llvm_bc" ELF section in "/home/maryam/Documents/github-repos/FFmpeg/ffmpeg", so skipping this entry
```

**Comment by me22bee** [comment]
I also test it on Debian with clang 10 based on this [CompilationGuide](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#FFmpeg): 
```
export CC=wllvm

export LLVM_COMPILER=clang

export LLVM_BITCODE_GENERATION_FLAGS='-g'


  PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig"   ./configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --ld="g++" \
  --bindir="$HOME/bin" \
  --enable-gpl \
  --enable-gnutls \
  --enable-libaom \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree 

PATH="$HOME/bin:$PATH" make
extract-bc ffmpeg
```

```
WARNING:Could not find ".llvm_bc" ELF section in "/home/maryam/Documents/github-repos/FFmpeg/ffmpeg", so skipping this entry
```

**Comment by me22bee** [comment]
sorry I closed it accidentally!

**Comment by ianamason** [comment]
Is `ffmpeg` an elf executable?  (see what:
```
file ffmpeg 
```
says).

Turn on the logging, and look at the log files.
Look at how it was built (in the logs), how it was linked etc.

**Comment by me22bee** [comment]
> file ffmpeg

yes it is:
```
file ffmpeg 
ffmpeg: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=cead7fc672b167dacab1a4ae1a81d2ce103849b3, stripped

```
It is built with CC which is set to wllvm and but it's linking with `ld` because of this:`--ld="g++" \`.
Do I need to change it?
Thanks

**Comment by me22bee** [comment]
In Debian, I used `CC` as an argument to `./configure` and it works! but I don't know why.
I used this:
```
  PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig"   LLVM_COMPILER=clang   LLVM_BITCODE_GENERATION_FLAGS='-g' /home/maryam/Documents/github-repos/FFmpeg/configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --bindir="$HOME/bin" \
  --cc=wllvm \
  --cxx=wllvm++ \
  --enable-gpl \
  --enable-gnutls \
  --enable-libaom \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree 

```
instead of this:
```
  PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig"   CC=wllvm CXX=wllvm++ LLVM_COMPILER=clang   LLVM_BITCODE_GENERATION_FLAGS='-g' /home/maryam/Documents/github-repos/FFmpeg/configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --bindir="$HOME/bin" \
  --enable-gpl \
  --enable-gnutls \
  --enable-libaom \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree 
```

but I had this warning again I don't know why!
```
WARNING:Did not recognize the compiler flag "-mllvm"
WARNING:Did not recognize the compiler flag "-stack-alignment=16"
```
Can you help me please?

**Comment by ianamason** [comment]
Those warnings are harmless usually. Using `ld` as the linker is also harmless, unless it uses flags that strip the executable.
What was the linking line like? Can't hurt to change it though.

**Comment by me22bee** [comment]
> What was the linking line like?

sorry I don't know where do I need to check to answer this question:(

**Comment by ianamason** [comment]
Look at the README about logging and debugging.

**Comment by ianamason** [comment]
Then scour the log for something like ` -o ffmpeg`

**Comment by haxkor** [comment]
Hi, i think this might be related to https://github.com/travitch/whole-program-llvm/issues/114

I had a similar bug.
```ERROR:FFmpeg/build/ffmpeg contained no __WLLVM segment``` means BitcodeGeneration was skipped when ffmpeg was built

**Comment by ianamason** [comment]
So all I can suggest is to turn on logging and watch what is happening. 
These sorts of things are possible:

1 The build system is using lto and so the .o files are actually bitcode. 

2 The build system has hard coded the compiler. 

Some detective work is required. File an issue, solve it, then bask in the fame 😜

**Comment by tylzh97** [comment]
FFmpeg‘s configure file does not using system variable "CC". 
If you want to using `wllvm` to build it , you shuold do someting like that:
`./configure --disable-yasm --cc=wllvm`
and then you can extract it with `extract-bc ffmpeg`

full commands here:
```
cd ffmpeg
./configure --disable-yasm --cc=wllvm
make
extract-bc ffmpeg
```

and you can find `ffmpeg.bc` here!
