### ISSUE TITLE
Clarifications on what happens to unrecognized flags?

### ISSUE THREAD

**Issue by Evan-Zhao** [travitch/whole-program-llvm#113]
So sometimes when these "rare" compiler flags are used, WLLVM gives this warning that it "did not recognize the compiler flag '...'"; for example:

> WARNING:Did not recognize the compiler flag "-mavx2"

After reading the source code it seems to me that these flags are simply kept, which means it apparently works for actual _flags_ (which takes no argument). I'm not sure if it works with options that takes arguments (`--flag value_0 [value_n]`), and it's not a concern in my use case but may be so for others.

Can we have some clarification for the consequences of this warning in the README or somewhere evident? Because I feel like this is the single most frequent warning that comes up when using WLLVM.

Thank you!

**Comment by ianamason** [comment]
I am traveling at the moment but I will write up some explanation when I return. 

But here is a super terse explanation. 

In a call to the compiler that is both compile and link we need to decompose this into a separate compile and link step. Thus it helps to decompose the flags into compile time and link time. 


Usually nothing breaks if it doesn’t get it exactly right.
