### ISSUE TITLE
BitcodeGeneration is skippen when .o files are input

### ISSUE THREAD

**Issue by haxkor** [travitch/whole-program-llvm#114]
Hi, first of all thank you for developing and maintaining  this great tool!

Using wllvm on SPEC benchmarks, I discovered a bug/feature:
The SPEC gcc version compiles smaller object files before building it together.
This results in a call of this form: ```clang one.o two.o -o final.o``` (lots of flags omitted)

This is due to the way the Arguments are parsed in arglistfilter.py, where each fileformat is assigned to one callback function.
.o files are assigned to ObjectFileCallback (Line 252)

This leads to af.inputFiles wrongfully being empty, which results in af.skipBytecodeGeneration() returning true when it should not.

**Comment by ianamason** [comment]
I will look into this when I am no longer traveling.

**Comment by ianamason** [comment]
Does gllvm have the same problem?

**Comment by ianamason** [comment]
I'm lost, neither
```
gcc foo.o bar.o -o foobar.o
```
nor 
```
clang foo.o bar.o -o foobar.o
```
will do what you are asking. Why would `wllvm` or `gclang`?
What am I missing here?

**Comment by haxkor** [comment]
Hi, you are missing that my example was a fictitious one :)
This is from an actual case where we tried to compile the SPEC gcc benchmark with `wllvm` 

InputFiles is empty, because all files ending with .o are matched to the objectFiles callback function, see Line 252 of arglistfilter.py

`
inputlist= ['-std=c99', '-v', '-m64', '-g', '-fno-strict-aliasing', '-fgnu89-inline', 'main.o', 'cc1-checksum.o', 'alias.o', 'alloca.o', 'alloc-pool.o', 'argv.o', 'attribs.o', 'auto-inc-dec.o', 'bb-reorder.o', 'bid2dpd_dpd2bid.o', 'bitmap.o', 'bt-load.o', 'c-lang.o', 'c-errors.o', 'c-lex.o', 'c-pragma.o', 'c-decl.o', 'c-typeck.o', 'c-convert.o', 'c-aux-info.o', 'c-common.o', 'c-opts.o', 'c-format.o', 'c-semantics.o', 'c-ppoutput.o', 'c-objc-common.o', 'c-dump.o', 'c-parser.o', 'c-gimplify.o', 'c-pretty-print.o', 'c-omp.o', 'caller-save.o', 'calls.o', 'cfg.o', 'cfganal.o', 'cfgbuild.o', 'cfgcleanup.o', 'cfgexpand.o', 'cfghooks.o', 'cfglayout.o', 'cfgloop.o', 'cfgloopanal.o', 'cfgloopmanip.o', 'cfgrtl.o', 'cgraph.o', 'cgraphbuild.o', 'cgraphunit.o', 'combine.o', 'combine-stack-adj.o', 'concat.o', 'convert.o', 'coverage.o', 'cp-demangle.o', 'cp-demint.o', 'cplus-dem.o', 'cpp_directives.o', 'cpp_lex.o', 'cpp_errors.o', 'cpp_expr.o', 'cpp_charset.o', 'cpp_macro.o', 'cpp_traditional.o', 'cpp_line-map.o', 'cpp_symtab.o', 'cpp_identifiers.o', 'cpp_mkdeps.o', 'cpp_pch.o', 'cpp_directives-only.o', 'crc32.o', 'cse.o', 'cselib.o', 'dbxout.o', 'dbgcnt.o', 'dce.o', 'ddg.o', 'debug.o', 'decContext.o', 'decimal128.o', 'decimal32.o', 'decimal64.o', 'decNumber.o', 'df-byte-scan.o', 'df-core.o', 'df-problems.o', 'df-scan.o', 'dfp.o', 'diagnostic.o', 'dojump.o', 'dominance.o', 'domwalk.o', 'double-int.o', 'dse.o', 'dwarf2asm.o', 'dwarf2out.o', 'dyn-string.o', 'ebitmap.o', 'emit-rtl.o', 'et-forest.o', 'except.o', 'explow.o', 'expmed.o', 'expr.o', 'fdmatch.o', 'fibheap.o', 'filename_cmp.o', 'final.o', 'fixed-value.o', 'floatformat.o', 'fold-const.o', 'fopen_unlocked.o', 'function.o', 'fwprop.o', 'gcse.o', 'genrtl.o', 'getopt1.o', 'getopt.o', 'getpwd.o', 'getruntime.o', 'ggc-common.o', 'ggc-page.o', 'gimple.o', 'gimple-iterator.o', 'gimple-low.o', 'gimple-pretty-print.o', 'gimplify.o', 'graph.o', 'graphds.o', 'graphite.o', 'graphite-blocking.o', 'graphite-clast-to-gimple.o','graphite-dependences.o', 'graphite-interchange.o', 'graphite-poly.o', 'graphite-ppl.o', 'graphite-scop-detection.o', 'graphite-sese-to-poly.o', 'gtype-desc.o', 'haifa-sched.o', 'hashtab.o', 'hex.o', 'hooks.o', 'host-ieee128.o', 'host-ieee32.o', 'host-ieee64.o', 'host-linux.o', 'i386.o', 'i386-c.o', 'ifcvt.o', 'incpath.o', 'init-regs.o', 'insn-attrtab.o', 'insn-automata.o', 'insn-emit.o', 'insn-extract.o', 'insn-modes.o', 'insn-opinit.o', 'insn-output.o', 'insn-peep.o', 'insn-preds.o', 'insn-recog.o', 'integrate.o', 'ipa-cp.o', 'ipa-inline.o', 'ipa-prop.o', 'ipa-pure-const.o', 'ipa-reference.o', 'ipa-struct-reorg.o', 'ipa-type-escape.o', 'ipa-utils.o', 'ipa.o', 'ira.o', 'ira-build.o', 'ira-costs.o', 'ira-conflicts.o', 'ira-color.o', 'ira-emit.o', 'ira-lives.o', 'jump.o', 'lambda-code.o', 'lambda-mat.o', 'lambda-trans.o', 'langhooks.o', 'lbasename.o', 'lcm.o', 'lists.o', 'loop-doloop.o', 'loop-init.o', 'loop-invariant.o', 'loop-iv.o', 'loop-unroll.o', 'loop-unswitch.o', 'lower-subreg.o', 'lrealpath.o', 'lto-cgraph.o', 'lto-streamer-in.o', 'lto-streamer-out.o', 'lto-section-in.o', 'lto-section-out.o', 'lto-symtab.o', 'lto-opts.o', 'lto-streamer.o', 'lto-wpa-fixup.o', 'make-relative-prefix.o', 'make-temp-file.o', 'partition.o', 'matrix-reorg.o', 'mcf.o', 'md5.o', 'mkstemps.o', 'mode-switching.o', 'modulo-sched.o', 'objalloc.o', 'obstack.o', 'omega.o', 'omp-low.o', 'optabs.o', 'options.o', 'opts-common.o', 'opts.o', 'params.o', 'passes.o', 'physmem.o', 'plugin.o', 'pointer-set.o', 'postreload-gcse.o', 'postreload.o', 'predict.o', 'pretty-print.o', 'print-rtl.o', 'print-tree.o', 'profile.o', 'recog.o', 'reg-stack.o', 'regcprop.o', 'regex.o', 'reginfo.o', 'regmove.o', 'regrename.o', 'regstat.o', 'reload.o', 'reload1.o', 'reorg.o', 'resource.o', 'rtl-error.o', 'rtl.o', 'rtlanal.o', 'rtlhooks.o', 'safe-ctype.o', 'sbitmap.o', 'sched-deps.o', 'sched-ebb.o', 'sched-rgn.o', 'sched-vis.o', 'sdbout.o', 'sel-sched-ir.o', 'sel-sched-dump.o', 'sel-sched.o', 'sese.o', 'sha1.o', 'simplify-rtx.o', 'sort.o', 'spaces.o', 'sparseset.o', 'splay-tree.o', 'sreal.o', 'stack-ptr-mod.o', 'statistics.o', 'stmt.o', 'stor-layout.o', 'store-motion.o', 'stringpool.o', 'strsignal.o', 'stub-objc.o', 'targhooks.o', 'timevar.o', 'tracer.o', 'tree-affine.o', 'tree-call-cdce.o', 'tree-cfg.o', 'tree-cfgcleanup.o', 'tree-chrec.o', 'tree-complex.o', 'tree-data-ref.o', 'tree-dfa.o', 'tree-dump.o', 'tree-eh.o', 'tree-if-conv.o', 'tree-inline.o', 'tree-into-ssa.o', 'tree-iterator.o', 'tree-loop-distribution.o', 'tree-loop-linear.o', 'tree-mudflap.o', 'tree-nested.o', 'tree-nrv.o', 'tree-object-size.o', 'tree-optimize.o', 'tree-outof-ssa.o', 'tree-parloops.o', 'tree-phinodes.o', 'tree-predcom.o', 'tree-pretty-print.o', 'tree-profile.o', 'tree-scalar-evolution.o', 'tree-sra.o', 'tree-switch-conversion.o', 'tree-ssa-address.o', 'tree-ssa-alias.o', 'tree-ssa-ccp.o', 'tree-ssa-coalesce.o', 'tree-ssa-copy.o', 'tree-ssa-copyrename.o', 'tree-ssa-dce.o', 'tree-ssa-dom.o', 'tree-ssa-dse.o', 'tree-ssa-forwprop.o', 'tree-ssa-ifcombine.o', 'tree-ssa-live.o', 'tree-ssa-loop-ch.o', 'tree-ssa-loop-im.o', 'tree-ssa-loop-ivcanon.o', 'tree-ssa-loop-ivopts.o', 'tree-ssa-loop-manip.o', 'tree-ssa-loop-niter.o', 'tree-ssa-loop-prefetch.o', 'tree-ssa-loop-unswitch.o', 'tree-ssa-loop.o', 'tree-ssa-math-opts.o', 'tree-ssa-operands.o', 'tree-ssa-phiopt.o', 'tree-ssa-phiprop.o', 'tree-ssa-pre.o', 'tree-ssa-propagate.o', 'tree-ssa-reassoc.o', 'tree-ssa-sccvn.o', 'tree-ssa-sink.o', 'tree-ssa-structalias.o', 'tree-ssa-ter.o', 'tree-ssa-threadedge.o', 'tree-ssa-threadupdate.o', 'tree-ssa-uncprop.o', 'tree-ssa.o', 'tree-ssanames.o', 'tree-stdarg.o', 'tree-tailcall.o', 'tree-vect-generic.o', 'tree-vect-patterns.o', 'tree-vect-data-refs.o', 'tree-vect-stmts.o', 'tree-vect-loop.o', 'tree-vect-loop-manip.o', 'tree-vect-slp.o', 'tree-vectorizer.o', 'tree-vrp.o', 'tree.o', 'unlink-if-ordinary.o', 'value-prof.o', 'var-tracking.o', 'varpool.o', 'varasm.o', 'varray.o', 'vec.o', 'vmsdbgout.o', 'web.o', 'xatexit.o', 'xcoffout.o', 'xexit.o', 'xmalloc.o', 'xmemdup.o', 'xstrdup.o', 'xstrerror.o', 'xstrndup.o', 'c-cppbuiltin.o', 'c-pch.o', 'cpp_files.o', 'cpp_init.o', 'cppdefault.o', 'intl.o', 'prefix.o', 'strerror.o', 'toplev.o', 'vasprintf.o', 'version.o', 'builtins.o', 'real.o', 'mini-gmp.o', 'spec_qsort/spec_qsort.o', '-lm', '-o', 'cpugcc_r']                          ~
`

**Comment by ianamason** [comment]
Can you give me a simple example of what you mean then. Because that looks more like
```
clang foo.o bar.o -o foobar
```
where `foobar` is going to be an executable.  For big things (like spec), if I were you, I would be using gllvm.

**Comment by haxkor** [comment]
Thx for the quick reply.
I now realize that my initial example was flawed, it should be `final` instead of `final.o` :)

Nonetheless, I am having trouble understanding what you need as I gave you a simple (unrealistic) example and an actual case where the problem occured, as well as an explanation of the bug.

Thank you for the gllvm recommendation! 
If you have time, why is gllvm better than wllvm for big projects? :)

**Comment by ianamason** [comment]
We ported wllvm to gllvm (written in golang) when we found it too slow for things like the linux kernel.
Since then, we pay more attention to gllvm, and only maintain wllvm when we have spare time. 

I asked for a small example because I really don't understand the problem you are claiming wllvm has.
Sorry. Not trying to be obtuse. I just want a small example so I know what you are talking about.

**Comment by ianamason** [comment]
For something like:
```
wllvm foo.o bar.o -o foobar
```
we do not generate bitcode, because it is just a link step. The bitcode has already been generated in the steps
that created `foo.o` and `bar.o`

**Comment by haxkor** [comment]
Ah, thanks for the explanation regarding the bitcode generation!
I should have added earlier that we added some functionality to wllvm, I guess the problem only occurs in that case, my bad.
The extra functionality links all bitcode segments together and then uses opt on it (so its like a LTO).
I somehow assumed this was a general wllvm problem, but if you say it is not I must apologize:)
