### ISSUE TITLE
Got error when build only two files.

### ISSUE THREAD

**Issue by ZH-Lee** [travitch/whole-program-llvm#115]
Hi, develeper:

I use the command:  "wllvm++ -pthread test1.cpp test2.cpp -o main"

and reported error:
Failed to find link section for section xxx.
undefined reference to "pthread_create".

But i have already add pthread.h header in test2.cpp and test1.cpp

is there something wrong with my command?

Regrads.

**Comment by ianamason** [comment]
What does 
```
clang++ -pthread test1.cpp test2.cpp -o main
```
say?

**Comment by ZH-Lee** [comment]
> What does
> 
> ```
> clang++ -pthread test1.cpp test2.cpp -o main
> ```
> 
> say?

It can build project successfully.

**Comment by ianamason** [comment]
OK I will look into it.

**Comment by ZH-Lee** [comment]
> OK I will look into it.

Hi, ianamason:
 Have the problem been solved?

the other problem occured when i build pbzip2. I got the Error:
objcopy: xxxx : Failed to find link section for section xxx

Is this the same problem with the pervious  one?

Regrads

**Comment by ianamason** [comment]
Various versions of `objcopy` have problems. Usually they can be ignored.
I can't duplicate your issue. Can you give me a small example (i.e so I don't have to write any C++)

**Comment by ZH-Lee** [comment]
> Various versions of `objcopy` have problems. Usually they can be ignored.
> I can't duplicate your issue. Can you give me a small example (i.e so I don't have to write any C++)

`
// test1.h
#ifndef TEST1_H_
#define TEST1_H_
#include <pthread.h>
#include <stdio.h>

extern int glb_ext;
extern pthread_mutex_t m;

void lock();
void unlock();

#endif
`

`
// test1.cpp
#include "test1.h"
pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;

int glb_ext = 1;

void lock() {
    pthread_mutex_lock(&m);
}

void unlock() {
    pthread_mutex_unlock(&m);
}
`

`
// test2.cpp
#include "test1.h"

using namespace std;

int glb_test;

void *Thread1(void* x) {
    lock();
    glb_test++;
    unlock();
    return nullptr;
}

void *Thread2(void* x) {
    lock();
    glb_test++;
    unlock();
    return nullptr;
}

int main() {
    pthread_t t[2];
    pthread_create(&t[0], nullptr, Thread1, nullptr);
    pthread_create(&t[1], nullptr, Thread1, nullptr);
    pthread_join(t[0], nullptr);
    pthread_join(t[1], nullptr);
    return 0;
}
`

**Comment by ZH-Lee** [comment]
> Various versions of `objcopy` have problems. Usually they can be ignored.
> I can't duplicate your issue. Can you give me a small example (i.e so I don't have to write any C++)


```
// test1.h
#ifndef TEST1_H_
#define TEST1_H_
#include <pthread.h>
#include <stdio.h>

extern int glb_ext;
extern pthread_mutex_t m;

void lock();
void unlock();

#endif

```


```
// test1.cpp
#include "test1.h"
pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;

int glb_ext = 1;

void lock() {
    pthread_mutex_lock(&m);
}

void unlock() {
    pthread_mutex_unlock(&m);
}

```


```
// test2.cpp
#include "test1.h"

using namespace std;

int glb_test;

void *Thread1(void* x) {
    lock();
    glb_test++;
    unlock();
    return nullptr;
}

void *Thread2(void* x) {
    lock();
    glb_test++;
    unlock();
    return nullptr;
}

int main() {
    pthread_t t[2];
    pthread_create(&t[0], nullptr, Thread1, nullptr);
    pthread_create(&t[1], nullptr, Thread1, nullptr);
    pthread_join(t[0], nullptr);
    pthread_join(t[1], nullptr);
    return 0;
}
```

**Comment by ianamason** [comment]
Thanks. It was an easy fix.
