### ISSUE TITLE
wllvm bitcode generation does not work properly with ccache

### ISSUE THREAD

**Issue by xuzi123** [travitch/whole-program-llvm#117]
I'm using wllvm to build opencv and generate bitcode.  When I changed the configure arguments and rebuild opencv, the .bc files was not generated.

Finally I found the reason is  opencv using ccache when compiling. So if the compiling command is the same with cached one, the wllvm compile command will not be executed.

Solution:
 Disable ccache before configure and build.
```export CCACHE_DISABLE=1 ```

I think wllvm can add a warning when ccache is enable.

**Comment by ianamason** [comment]
I don’t think this is wllvm’s problem.

**Comment by xuzi123** [comment]
> I don’t think this is wllvm’s problem.

OK. At least this issue can remind other people.
