### ISSUE TITLE
wllvm build whole linux failure

### ISSUE THREAD

**Issue by iaGuoZhi** [travitch/whole-program-llvm#118]
## My environment
LLVM: 7.0.0
wllvm: 1.3.1
linux source code version: 4.19

## My steps
1. export LLVM_COMPILER=clang
2. make O=build CC=wllvm allyesconfig
3. make O=build CC=wllvm -j8

## Error info:

compiler lacks asm-goto support
![Screenshot_20210901_214859](https://user-images.githubusercontent.com/41318515/131683214-b62a0adb-5ef5-442f-a30a-2063631dbda7.png)

I want to analysis on the whole linux kernel, which require compile linux kernel into a single bitcode file, So I choosed wllvm. LLVM 7.0.0 has already support asm-goto and can compile linux kernel. Is wllvm does not support asm-goto?

**Comment by ianamason** [comment]
It is clang that is causing the complaint. Wllvm is just a wrapper. Try building it with clang. See what happens.

**Comment by ianamason** [comment]
Can I close this?
