### ISSUE TITLE
llvm-link: No such file even with LLVM_COMPILER_PATH set

### ISSUE THREAD

**Issue by croemheld** [travitch/whole-program-llvm#120]
Even though there is a similar issue #119 that also involves the `llvm-link` program, the setup is a bit different so I decided its best to create a new issue.

I built the llvm-project with commit ef976337f581dd8a80820a8b14b4bbd70670b7fc. Before using wllvm to compile the vmlinux binary, I used the following exports:

```
export LLVM_COMPILER=clang
export LLVM_COMPILER_PATH=/home/roemheld/Repositories/llvm-project/build/bin
```
When the compilation is done, I use `extract-bc vmlinux` to create my `vmlinux.bc` file. However, I get a message saying:

```
$ extract-bc vmlinux
/home/roemheld/Repositories/llvm-project/build/bin/llvm-link: No such file or directory
```
Perplexed, I checked the output of `extract-bc --help`:

```
$ extract-bc --help
[...]
  --linker LLVMLINKER, -l LLVMLINKER
                        The LLVM bitcode linker to use. Default
                        "/home/roemheld/Repositories/llvm-
                        project/build/bin/llvm-link"
[...]
```
So the default path seems to have been correctly imported from the exported variable above. An additional check:

```
/home/roemheld/Repositories/llvm-project/build/bin/llvm-link --help
```
displays the help dialog from my `llvm-link` program. Furthermore, directly specifying the linker in `extract-bc` via its `--linker` argument yields the same result:

```
$ extract-bc -l /home/roemheld/Repositories/llvm-project/build/bin/llvm-link vmlinux
/home/roemheld/Repositories/llvm-project/build/bin/llvm-link: No such file or directory
```

I installed `wllvm` via `pip3`. The current version is 1.3.1.

**Comment by ianamason** [comment]
What does `wllvm-sanity-checker` say?

**Comment by croemheld** [comment]
Output of `wllvm-sanity-checker`:

```
$ wllvm-sanity-checker 
wllvm version: 1.3.1
wllvm released: April 10 2021

Logging output to standard error.
Logging level not set, defaulting to WARNING.

We are using clang.

The C compiler /home/roemheld/Repositories/llvm-project/build/bin/clang is:

        clang version 14.0.0 (git@github.com:llvm/llvm-project.git ef976337f581dd8a80820a8b14b4bbd70670b7fc)

The C++ compiler /home/roemheld/Repositories/llvm-project/build/bin/clang++ is:

        clang version 14.0.0 (git@github.com:llvm/llvm-project.git ef976337f581dd8a80820a8b14b4bbd70670b7fc)

The bitcode linker /home/roemheld/Repositories/llvm-project/build/bin/llvm-link is:

        LLVM version 14.0.0git

The bitcode archiver /home/roemheld/Repositories/llvm-project/build/bin/llvm-ar is:

        LLVM version 14.0.0git

Not using a bitcode store.

```

**Comment by ianamason** [comment]
Well if there is a `/home/roemheld/Repositories/llvm-project/build/bin/llvm-link` executable, then it must be complaining about something else. Turn on debugging and log to a file and take a closer look at what it is doing when it asplodes.

**Comment by croemheld** [comment]
I tried to inspect the source code of wllvm. I tried reproducing the code up until this point (I created a manifest file in order to get all file names into one array in python):

```
$ python3
>>> file = open("vmlinux.llvm.manifest")
>>> fileNames = file.read().splitlines()
>>> cmd = ["/home/roemheld/Repositories/llvm-project/build/bin/llvm-link", "-v"]
>>> cmd.append("-o=vmlinux.bc")
>>> cmd.extend([x for x in fileNames if x != ''])
>>> proc = subprocess.Popen(cmd)
```

which yields the same result as described above. However, when trying to find out what went wrong, I noticed that I was working in a virtualenv (since I installed wllvm in a virtualenv). By changing the last line in the python terminal to:

```
>>> shellcmd = ' '.join(cmd)
>>> proc = subprocess.Popen(shellcmd, shell=True)
```
the output changes to:

```
>>> Loading '/home/roemheld/Repositories/linux/arch/x86/kernel/.head64.o.bc'
Linking in '/home/roemheld/Repositories/linux/arch/x86/kernel/.head64.o.bc'
Loading '/home/roemheld/Repositories/linux/arch/x86/kernel/.ebda.o.bc'
Linking in '/home/roemheld/Repositories/linux/arch/x86/kernel/.ebda.o.bc'
[...]
Loading '/home/roemheld/Repositories/linux/init/.calibrate.o.bc'
Linking in '/home/roemheld/Repositories/linux/init/.calibrate.o.bc'
Writing bitcode...
```

So I'm not exactly sure if and how working in a virtualenv influences this behavior exactly. Maybe I'll leave this in case someone other might encounter this issue.

**Comment by ianamason** [comment]
That's bizarre.

I think my advice is to use gllvm.

**Comment by croemheld** [comment]
@ianamason I managed to find the real underlying issue. Its just that the number of arguments passed to the `llvm-link` program are at fault here. Even though the `ARG_MAX` configuration seems to support the large amount of individual bitcode files, it seems to fail at a certain point. Furthermore, instead of throwing an "Argument list too long" or similar error the displayed message simply says that the linker was not found. This also adds to the confusion...

By dividing up the `subprocess.Popen()` call, I was able to link the files one by one. This might be really slow, but it at least circumvents the issue with too many files being passed to the linker.

```python
import subprocess

rfile = open('vmlinux.llvm-manifest')
filenames = rfile.read().splitlines()
filenames = [x for x in filenames if x != '']
cmd = ['/home/roemheld/Repositories/llvm-project/build/bin/llvm-link']
cmd.append('-v')
cmd.append('-o=vmlinux.bc')
first, remaining = filenames[0], filenames[1:]
cmd.append(first)

# Use check_call to wait until process finished
subprocess.check_call(cmd)

# Add vmlinux.bc to command
cmd.append('vmlinux.bc')

for x in remaining:
    # Replace filename and link files one by one
    cmd[3] = x
    subprocess.check_call(cmd)
```

With this the issue can be closed as the real underlying problem was just the number of arguments. Granted, you rarely ever link a vast amount of files but for `vmlinux` this is necessary.

**Comment by ianamason** [comment]
Well done.

Yes indeed, that rings a bell. 

We handle that [here](https://github.com/SRI-CSL/gllvm/blob/938e8515ce5d09f7903e902bdb6f1c54fc0495c9/shared/extractor.go#L607) in gllvm. 

Your welcome to do something similar for wllvm in a pull request, if you feel like becoming a legend.

**Comment by ianamason** [comment]
Actually using these wrappers on the kernel is surprisingly popular, so I am sure someone will benefit amongst
for those of you unwilling to use gllvm :-)
