### ISSUE TITLE
Compile Kernel

### ISSUE THREAD

**Issue by hrshy0629** [travitch/whole-program-llvm#123]
Hi, I want to use WLLVM (clang compiler) to compile the Linux kernel. In fact, I readily do it! But when I use clang to compile the Linux kernel, I fail! The WLLVM is magic, it did what Clang didn't.  I wonder why it is?

**Comment by ianamason** [comment]
Only a few versions of the linux kernel compile using clang.  Sorry. This is not an issue with wllvm.
