### ISSUE TITLE
any suggestions to solve "symbol multiply defined!"

### ISSUE THREAD

**Issue by jmp0x7c00** [travitch/whole-program-llvm#124]
wllvm is really good tool. Thanks ! but when I extracted bc from .so file , "symbol multiply defined!" reported
```debug
xx@ubuntu2004:~/gbc_sgx$ extract-bc enclave.signed.so
error: Linking globals named 'mmu_step': symbol multiply defined!
```
and my manifest:
```
/home/xx/gbc_sgx/.audio.o.bc
/home/xx/gbc_sgx/.cpu.o.bc
/home/xx/gbc_sgx/.debugger.o.bc
/home/xx/gbc_sgx/.disassembler.o.bc
/home/xx/gbc_sgx/.emu.o.bc
/home/xx/gbc_sgx/.fileio.o.bc
/home/xx/gbc_sgx/.lcd.o.bc
/home/xx/gbc_sgx/.mmu.o.bc
/home/xx/gbc_sgx/.state.o.bc
/home/xx/gbc_sgx/.mmu.o.bc
/home/xx/gbc_sgx/.lcd.o.bc
/home/xx/gbc_sgx/.fileio.o.bc
/home/xx/gbc_sgx/.disassembler.o.bc
/home/xx/gbc_sgx/.audio.o.bc
/home/xx/gbc_sgx/.cpu.o.bc
/home/xx/gbc_sgx/.debugger.o.bc
/home/xx/gbc_sgx/.state.o.bc
/home/xx/gbc_sgx/.emu.o.bc
/home/xx/gbc_sgx/Enclave/.Enclave_t.o.bc
/home/xx/gbc_sgx/Enclave/.Enclave.o.bc
/home/xx/gbc_sgx/Enclave/.test.o.bc
```

I searched this problem , and found this:
#62  and
https://discourse.llvm.org/t/llvm-link-symbol-multiply-defined/718/4

I know it is blamed to LLVM-LINK.  but how can I solve this problem? any suggestion is appreciated!

**Comment by ianamason** [comment]
Edit the bitcode? 
Use the bitcode without linking it all into one file?

**Comment by tandf** [comment]
I'm also getting the "symbol multiply defined" error. I was thinking about editing the IR files (to specific, .ll files) and changing `@global = dso_local global i32 0, align 4, !dbg !28` to `@global = external dso_local global i32`. Then I found that the `--only-needed` option for llvm-link solves the problem. I'm using llvm-link-13. Hope this helps.
