### ISSUE TITLE
Building apache httpd with apr source code included

### ISSUE THREAD

**Issue by emugnier** [travitch/whole-program-llvm#125]
Hi, 
I am trying to build apache with apr source code included in the httpd binary using:
```bash
CC="wllvm" CXX="wllvm++" CPPFLAGS="-I${HOME}/ac_sym/s2e/source/s2e/guest/common/include" CFLAGS="-g -O0" ../configure --prefix=${HOME}/ac_sym/apache/httpd --with-pcre=${HOME}/ac_sym/apache/pcre --with-included-apr --enable-mods-static=few --enable-static-support
make
```
The option `with-included-apr` is supposed to include `apr` into the httpd binary.

However after using the `extract-bc` and `llvm-dis` the only information that I get about apr functions are something like:
```llvm
declare dso_local i32 @apr_ipsubnet_test(%struct.apr_ipsubnet_t*, %struct.apr_sockaddr_t*) #2
```
The body of the function is not included in the llvm bitcode. Is there a way to include the apr library in the httpd llvm bitcode?

**Comment by ianamason** [comment]
So what I would do (and have done in the past) is just build the dependencies that you want with wllvm (or better yet gllvm)
and link the bitcode by hand.  If you take a look [here](https://github.com/SRI-CSL/OCCAM-Benchmarks/tree/master/examples/portfolio/apache) you should be able to see what we used to do.
