### ISSUE TITLE
Building Linux kernel modules

### ISSUE THREAD

**Issue by Yukinarii** [travitch/whole-program-llvm#126]
Hi, 

I am trying to compile linux modules with wllvm in the hope of generating bitcode from the binary files. Generally, after configuration, I compile it with gcc by just make modules to see if everything goes well, and it does. The `.ko` files are generated.

Then, I reconfigure the kernel `make CC=wllvm defconfig`, setup the llvm compiler as clang `export LLVM_COMPILER=clang` and the default C compiler as `export CC=wllvm`, and compile the modules again with `make CC=wllvm -no-integrated-as modules`. The compilation does not produce any error message, and finishes smoothly. However, I can't find any expected `.ko` file.

Did I miss or do anything anything wrong?

**Comment by ianamason** [comment]
What happens if you just try with clang?

**Comment by Yukinarii** [comment]
Hi,
Thank you for the response! I tried it with only clang with the following steps:
`make CC=clang defconfig`
`export CC=clang`
`make CC=clang -no-integrated-as modules`

I got the same results as with wllvm: no `.ko` files are generated, though there is no error message. I also noticed that the compilation log is quite similar between wllvm and clang, but completely different from gcc's.
