### ISSUE TITLE
wllvm fails with make

### ISSUE THREAD

**Issue by fanghejun** [travitch/whole-program-llvm#128]
# wllvm fails with only make

Hi,
Today I've successfully built the Assimp package  with **cmake+make**, but now I need to build the Packjpg package that ships with only a **make** build system. I work on KLEE's docker image and clang6.0 .

Here is the step:

```
$ export LLVM_COMPILER=clang
$ export WLLVM_OUPUT=DEBUG
$ export CC=/usr/local/bin/wllvm
$ export CXX=/usr/local/bin/wllvm++
$ export CFLAGS="-g -O1 -Xclang -disable-llvm-passes -D__NO_STRING_INLINES  -D_FORTIFY_SOURCE=0 -U__OPTIMIZE__"
$ CC=wllvm CXX=wllvm++ make
```

but here are some outputs I get :

```
wllvm -E -c -o bitops.o bitops.cpp -I. -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer -std=c++14 -DUNIX
clang: error: unknown argument: '-fsched-spec-load'
ERROR:Failed to compile using given arguments: [-E -c -o bitops.o bitops.cpp -I. -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer -std=c++14 -DUNIX]
Makefile:31: recipe for target 'bitops.o' failed
make: *** [bitops.o] Error 1
```

Is the use of wllvm tool only based on cmake + make or configure + make? Because I checked the use examples of wllvm and Klee's official wllvm tutorial, which are only about these two. Or is it OK to run make directly?

This is my confusion. Looking forward to any reply. Thank you!

**Comment by ianamason** [comment]
Notice that it is clang that does not recognize  `-fsched-spec-load`  so I think if you tried:
```
clang -E -c -o bitops.o bitops.cpp -I. -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer -std=c++14 -DUNIX
```
you would get an error. So thus it is not an issue with wwlvm.

**Comment by fanghejun** [comment]
Your reply is very helpful to me! 
After I try to change the parameters in question, clang will also report other errors. So finally, I want to confirm to you that the usage of my compilation command is correct?

`CC=wllvm CXX=wllvm++ make`

**Comment by ianamason** [comment]
Yes, once you are sure
```
CC=clang CXX=clang++ make
```
works without errors.

**Comment by fanghejun** [comment]
thanks a lot!
