### ISSUE TITLE
How do I know what flags to use when turning the bitcode back to an executable?

### ISSUE THREAD

**Issue by goerlibe** [travitch/whole-program-llvm#132]
Hello,

_Background (feel free to skip this section if you are not interested) :_
I am working on DiscoPoP, a tool that helps you to discover parallelization opportunities and suggests openmp constructs to be used. It currently works well with some benchmarks but we want to test it on larger applications as well.
DiscoPoP works by analyzing source code using llvm passes. It also changes the llvm-ir to add some instrumentation e.g. before using/writing a variable. When the program is then compiled and run we can record runtime dependencies between different variables, functions etc. . These dependencies are then analyzed to find opportunities for parallelization.

_(start reading here if you skipped the background section)_
The idea now is to use wllvm to make it easier to use our tool on larger programs. This way we can just drop-in-replace the compiler used in some large project with wllvm when building it. It is then much simpler to work with just a single .bc (or .ll) file. We make some changes (add instrumentation) on the .bc and then we need to turn it back to an executable. This last step is where I have trouble...

While trying to analyze ffmpeg I am using the approach suggested in step 6 of the ubuntu tutorial but I have trouble figuring out what flags I need to add to the command in order to get it to work properly. Most larger programs use a lot of libraries so we need to add the corresponding flags (-lm -lncurses -lpthread ....) . I can research manually by looking at the makefile or the executed commands etc. to see what flags the original build process used, but it is very tedious for large projects and I am looking for a way to do this automatically.

The build system does call the linker (wllvm++) with all the correct flags so wllvm should know about them. Is there a way to extract them? Or is there a way to determine the needed flags (at least those for the libraries) from the .o file or the .bc file?

Any help is greatly appreciated!

**Comment by ianamason** [comment]
Interesting direction to develop the tool. But:

1. You should be using gllvm NOT wllvm. 

2. I am camping in the sawtooth wilderness with internet only while eating lunch in Stanley. 

I’ll be back next week. In the meantime page in using gllvm. There may also be some open issues that are pertinent.

**Comment by ianamason** [comment]
So I am back on line. 
Lets start by asking what is wrong with just scanning the log files for the calls?
Not super convenient, but we can go from there.

I am going to close this issue, and ask that you open it up, perhaps by cutting and pasting over [here.](https://github.com/SRI-CSL/gllvm)

**Comment by ianamason** [comment]
@goerlibe  are you still interested in solving this?

**Comment by goerlibe** [comment]
Hi, thanks for taking the time and sorry for my late reply. I am a student who only works a few hours on the project and in the last time I was focused on some other tasks (we were finally able to analyze ffmpeg 🥳), and YES, I am absolutely interested in figuring out the flags to link all the correct libraries in a general use case.

I will try gllvm and see how it goes. Then I will have another look at the library flag issue. If the logs are somewhat well-formed it should be rather easy to extract them from there.

On the other hand I guess it would be a nice feature for wllvm/gllvm to allow to extract the flags in an easy way (part of the work is already done, as you differentiate between compiler and linker commands and parse the flags).
Maybe there should be an extract-bc option to also extract the used linker command. Obviously this requires some under-the-hood-changes to have them available at that point in the process. Possibly the implementation would look similar to the way extract-bc finds the .bc files to create the whole-program-llvm-ir file?
Another way would be to (on-demand) create separate log files for compile and link commands that were used. Then we don't have to go through the entire log, but only through those files to get what we need.

I will just leave this is a suggestion right here and I will come back to you on the gllvm github once it becomes more needed for us.

**Comment by ianamason** [comment]
While you were away I added another log level to gllvm called AUDIT, the README.md explains more.
