### ISSUE TITLE
ERROR:WLLVM Failed to execute: ['file', path to file]

### ISSUE THREAD

**Issue by KaranFriends** [travitch/whole-program-llvm#139]
I am trying to build python project, and my end goal is to generate binary of python.

I installed wllvm as discribed in the readme file.
It is properly installed, only one customization I have is I have used my own version of clang.
The path to clang binary is set in PATH variable, and LLVM_COMPILER = clang.

PATH=/root/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/remote-cli:/home/llvm-project/build/bin:/home/binutils-src/binutils_install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LLVM_COMPILER=clang

when I try to configure python project I just do
../configure CC="wllvm -O0" CXX="wllvm++ -O0"
make

ERROR:WLLVM Failed to execute: ['file', '/home/cpython/build/Modules/atexitmodule.o']
WARNING:wllvm: exception case: [Errno 2] No such file or directory: 'file'

This is the error that I am getting during make.

**Comment by ianamason** [comment]
You need to have the Unix utility "file" installed.  That's what it is complaining about.

**Comment by KaranFriends** [comment]
Thank you so much, it worked for me. Actually I am using a bare container, in which I am using wllvm.

**Comment by ianamason** [comment]
Yes it is a common problem. Klee's container didn't have it installed for a while, so I saw this daily :-(
