### ISSUE TITLE
Specific version of LLVM unsupported

### ISSUE THREAD

**Issue by 1rre** [travitch/whole-program-llvm#140]
/wllvm/compilers.py checks only for the exact string "clang", meaning eg. "clang-14.0.6" doesn't get recognised as a form of clang and results in errors.

**Comment by ianamason** [comment]
Please read the README. Specifically the bit about  [LLVM_CC_NAME](https://github.com/SRI-CSL/whole-program-llvm/blob/master/README.md#usage)

**Comment by 1rre** [comment]
I was doing that, but for some reason it still wouldn't work - there's a high chance it's me that's doing something wrong though hence the closed issue

**Comment by ianamason** [comment]
Try using the sanity checker. Also gllvm is faster/better than wllvm.
