### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by JoraGevorgyan** [travitch/whole-program-llvm#142]
Looks like it doesn't work with new versions of clang and linux, there are some issues connected with flags and linker.
(I can show logs if needed)

**Comment by ianamason** [comment]
Yes some logs would be good. It should be agnostic about clang versions.

**Comment by ianamason** [comment]
P.S. you should really be using gllvm, but it hasn't been updated lately, but then again, noone has complained.

**Comment by JoraGevorgyan** [comment]
> 

I tried it too, and yes it gives very similar issues like wllvm

**Comment by JoraGevorgyan** [comment]
[here are logs and output of make](https://drive.google.com/drive/folders/1hBGbc1XfgnZdxo4cJ4Lhv3y8nRuIVnAI?usp=sharing)

if any other details needed, I'll be happy to help as I can.

**Comment by ianamason** [comment]
Oh you're trying to compile linux? Yes I doubt that it would work with just clang alone. did you try that?
The linux kernel only was compilable with clang for a short amount of time.

This has nothing to do with either wllvm or gllvm.

**Comment by JoraGevorgyan** [comment]
It works now, with "clang only" it compiles, but with wllvm fails

**Comment by JoraGevorgyan** [comment]
Actually I found a [repository](https://github.com/ZHYfeng/Generate_Linux_Kernel_Bitcode.git) which helps to get bitcode of linux kernel, but I just thought to open this issue for you to know, that it exits.
