### ISSUE TITLE
`ccache` detection fails on macOS

### ISSUE THREAD

**Issue by jryans** [travitch/whole-program-llvm#144]
The `ps` command on macOS does not support the option `--no-header`, so the change from https://github.com/travitch/whole-program-llvm/pull/138 causes all commands to fail on that platform.

Perhaps it should be guarded as Linux only, or rewritten to work without `--no-header`.

**Comment by ianamason** [comment]
Got a fix for this?

**Comment by jryans** [comment]
I should be able to cook something up in the next few days. 🙂

**Comment by ianamason** [comment]
Thank you!
