### ISSUE TITLE
Can I use `wllvm` with `afl-clang-fast`?

### ISSUE THREAD

**Issue by lijunqiang123** [travitch/whole-program-llvm#147]
Hi. I want to use `afl-clang-fast` to instrument the program first, and then, use `wllvm` to get `llvm IR` code.  To finish this, I try to set:
```
export LLVM_COMPILER=afl-clang-fast
CC = wllvm
```
But it didn't work. Here is the error message:
![image](https://github.com/travitch/whole-program-llvm/assets/22146584/736d2412-ca10-4ed3-abfa-fa628cfbd168)

I don't know what should I do to achieve this. Could you please help me?

**Comment by ianamason** [comment]
Please read the README.

**LLVM_COMPILER**  sets the type of compiler. In your case it should be **clang**. Then you would set **LLVM_CC_NAME** or **LLVM_CXX_NAME** or both.

**Comment by lijunqiang123** [comment]
Thank you for your reply. I try to set: 
```
export LLVM_COMPILER=clang
export LLVM_CC_NAME =afl-clang-fast
CC = wllvm
```
But it didn't work. Here is the error message: 
![image](https://github.com/travitch/whole-program-llvm/assets/22146584/82a1652a-9aff-48c7-a5b8-f4b5e0126d69)
