### ISSUE TITLE
Autotooled programs won't compile

### ISSUE THREAD

**Issue by Tellendil** [travitch/whole-program-llvm#19]
When using a program built with autotool (such as Apache, or MySQL server), the configuration phase will not succeed, as the configure script creates conftest files, which it then removes with a "rm". As wllvm creates a hiddend directory in there, the configure script would fail.

However, using clang directly for the configure and then wllvm won't work, as the compiler is often hardcoded during the configure phase.

Would it be possible to have a toggle such as en environment variable on the wllvm and wllvm++ scripts, in which case these would only do the things a normal clang would do ?

**Comment by ianamason** [comment]
Seems like a reasonable request.  I'll look into it. Certainly we want to be able build things like Apache and MySQL if we can.

**Comment by travitch** [comment]
hmm, it works for some autotooled programs.  I'll have to see what apache and mysql are doing, in particular.  I remember compiling mysql with it before - at the time I noticed that the build process was doing some very strange things.  It was a bit difficult to get all the way through, though I can't remember the details right now.

**Comment by Tellendil** [comment]
Hey !

Sorry for the delay.

Here is a sample config.log of a version of Apache I need to work on with wllvm : 

First using the normal wllvm: https://www.dropbox.com/s/k3d6bbf8m085ewb/wllvm-basic?dl=0
Then by disabling the second phase of wllvm : https://www.dropbox.com/s/hkil1laz23urkbp/with_patch?dl=0

I may build other examples or give more details if ever needed.

**Comment by ianamason** [comment]
OK so I gather you are building (an old version 0.9.4?) of Apache Portable Runtime on Linux. 
But I still don't seem to be able to reproduce the problem. I can build it (1.5.1) on both mac and linux. On the mac I see some complaints about directories no being empty, but  it doesn't fail out.




It is easy enough to put in an environment variable to prevent the second pass from happening.

Got an opinion Tristan?

**Comment by travitch** [comment]
I haven't seen that one either, what version of apache (or APR?) are you trying to build exactly, @Tellendil ?  I suppose we are generating some normal files alongside the expected configure outputs.  If configure deletes the outputs it was expecting, but not ours, then we would expect the `rmdir` to fail.

I suppose the environment variable is the way to go - we'll never be able to figure out reliably when we are being run in a configure script.

**Comment by Tellendil** [comment]
@travitch I try to build version 2.2 of apache.

It works indeed with newer versions, but old versions of apache (and mysql and a few others) do not work that well.

**Comment by ianamason** [comment]
@travitch   wanna close this?
