### ISSUE TITLE
How to get the bitcode file from a program that calls a library

### ISSUE THREAD

**Issue by xiedingbao** [travitch/whole-program-llvm#28]
I want to test a library with klee. I built the library using wllvm/wllvm++ and get the static link library libtest.a.
And then I write a test file to call the library. At last I compile the file against the library using command wllvm++ test.cc libtest.a. I get the bitcode file by executing extract-bc a.out.
However when running klee on this bitcode file, klee complained can't load a symbol.
I wonder is that the correct way to get the bitcode file or do I miss anything?

**Comment by ianamason** [comment]
You would first get the bitcode associated with the library:

extract-bc libtest.a

which should give you something like libtest.a.bc  (not sure if the .a is still there)

you could then compile test.cc to get test.bc  and then link that against libtest.a.bc

this last step can be done with just clang. Sorry my clang-fu is rusty so I'm not gonna
try and give you actual commands, just a high level picture. Hope that helps.

**Comment by xiedingbao** [comment]
After executing command extract-bc libtest.a, I get a .bca file which can not be linked against another bc file using llvm-link. How could I get the bitcode associated with the library?

**Comment by ianamason** [comment]
I guess these days a bca isn't as useful as it used to be when llvm-ld roamed the planet.

Here is an example (I added it to SRI's README.md)

```
    export LLVM_COMPILER=clang
    tar xvfz jansson-2.7.tar.gz
    cd jansson-2.7
    CC=wllvm ./configure
    make
    mkdir bitcode
    cp src/.libs/libjansson.a bitcode
    cd bitcode
    extract-bc src/.libs/libjansson.a
    llvm-ar x libjansson.bca
    ls -la
```
