### ISSUE TITLE
a detailed instruction on how to use wllvm for beginner 

### ISSUE THREAD

**Issue by bcko** [travitch/whole-program-llvm#30]
Hello, I am new to wllvm. 
I am having a difficulty actually figuring out how to use wllvm. 
according to one of the closed issue, #19 Autotooled programs won't compile. 
@ianamason mentions that he built Apache's httpd 2.4.12 on Ubuntu 14.04. 

I was wondering if anyone can give a detailed instruction on how to build Apache httpd 2.4.12 on Ubuntu 14.04. 
Thank you so much!

below is what I did

I downloaded httpd 2.4.12 and also pasted apr and apr-util into srclib.

Terminal
CC=/home/bcko/Downloads/whole-program-llvm-master/wllvm ./configure --with-included-apr

Output
checking for chosen layout... Apache
checking for working mkdir -p... yes
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
configure: 
configure: Configuring Apache Portable Runtime library...
configure: 
configuring package in srclib/apr now
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
Configuring APR library
platform: x86_64-unknown-linux-gnu
checking for working mkdir -p... yes
APR Version: 1.5.2
checking for chosen layout... apr
checking for gcc... /home/bcko/Downloads/whole-program-llvm-master/wllvm
checking whether the C compiler works... no
configure: error: in `/home/bcko/Downloads/httpd-2.4.12/srclib/apr':
configure: error: C compiler cannot create executables
See `config.log' for more details
configure failed for srclib/apr

config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --with-included-apr

## --------- ##

hostname = bcko-VirtualBox
uname -m = x86_64
uname -r = 3.19.0-18-generic
uname -s = Linux
uname -v = #18-Ubuntu SMP Tue May 19 18:31:35 UTC 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games

## ----------- ##

configure:3077: checking for chosen layout
configure:3079: result: Apache
configure:3882: checking for working mkdir -p
configure:3898: result: yes
configure:3907: checking for grep that handles long lines and -e
configure:3965: result: /bin/grep
configure:3970: checking for egrep
configure:4032: result: /bin/grep -E
configure:4048: checking build system type
configure:4062: result: x86_64-unknown-linux-gnu
configure:4082: checking host system type
configure:4095: result: x86_64-unknown-linux-gnu
configure:4115: checking target system type
configure:4128: result: x86_64-unknown-linux-gnu
configure:4158: 
configure:4160: Configuring Apache Portable Runtime library...
configure:4162: 

## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_CC_set=set
ac_cv_env_CC_value=/home/bcko/Downloads/whole-program-llvm-master/wllvm
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_mkdir_p=yes
ac_cv_path_EGREP='/bin/grep -E'
ac_cv_path_GREP=/bin/grep
ac_cv_target=x86_64-unknown-linux-gnu

## ----------------- ##

APACHECTL_ULIMIT=''
APR_BINDIR=''
APR_CONFIG=''
APR_INCLUDEDIR=''
APR_VERSION=''
APU_BINDIR=''
APU_CONFIG=''
APU_INCLUDEDIR=''
APU_VERSION=''
AP_BUILD_SRCLIB_DIRS=''
AP_CLEAN_SRCLIB_DIRS=''
AP_LIBS=''
AWK=''
BUILTIN_LIBS=''
CC='/home/bcko/Downloads/whole-program-llvm-master/wllvm'
CFLAGS=''
CORE_IMPLIB=''
CORE_IMPLIB_FILE=''
CPP=''
CPPFLAGS=''
CRYPT_LIBS=''
CXX=''
CXXFLAGS=''
DEFS=''
DSO_MODULES=''
DTRACE=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/bin/grep -E'
ENABLED_DSO_MODULES=''
EXEEXT=''
EXTRA_CFLAGS=''
EXTRA_CPPFLAGS=''
EXTRA_CXXFLAGS=''
EXTRA_INCLUDES=''
EXTRA_LDFLAGS=''
EXTRA_LIBS=''
GREP='/bin/grep'
HTTPD_LDFLAGS=''
HTTPD_VERSION='2.4.12'
INCLUDES=''
INSTALL=''
INSTALL_DSO=''
INSTALL_PROG_FLAGS=''
INTERNAL_CPPFLAGS=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LN_S=''
LOAD_ALL_MODULES=''
LTCFLAGS=''
LTFLAGS=''
LTLIBOBJS=''
LT_LDFLAGS=''
LUA_CFLAGS=''
LUA_LIBS=''
LYNX_PATH=''
MATH_LIBS=''
MKDEP=''
MKINSTALLDIRS=''
MK_IMPLIB=''
MODULE_CLEANDIRS=''
MODULE_DIRS=''
MOD_ACCESS_COMPAT_LDADD=''
MOD_ACTIONS_LDADD=''
MOD_ALIAS_LDADD=''
MOD_ALLOWMETHODS_LDADD=''
MOD_ASIS_LDADD=''
MOD_AUTHNZ_FCGI_LDADD=''
MOD_AUTHNZ_LDAP_LDADD=''
MOD_AUTHN_ANON_LDADD=''
MOD_AUTHN_CORE_LDADD=''
MOD_AUTHN_DBD_LDADD=''
MOD_AUTHN_DBM_LDADD=''
MOD_AUTHN_FILE_LDADD=''
MOD_AUTHN_SOCACHE_LDADD=''
MOD_AUTHZ_CORE_LDADD=''
MOD_AUTHZ_DBD_LDADD=''
MOD_AUTHZ_DBM_LDADD=''
MOD_AUTHZ_GROUPFILE_LDADD=''
MOD_AUTHZ_HOST_LDADD=''
MOD_AUTHZ_OWNER_LDADD=''
MOD_AUTHZ_USER_LDADD=''
MOD_AUTH_BASIC_LDADD=''
MOD_AUTH_DIGEST_LDADD=''
MOD_AUTH_FORM_LDADD=''
MOD_AUTOINDEX_LDADD=''
MOD_BUCKETEER_LDADD=''
MOD_BUFFER_LDADD=''
MOD_CACHE_DISK_LDADD=''
MOD_CACHE_LDADD=''
MOD_CACHE_SOCACHE_LDADD=''
MOD_CASE_FILTER_IN_LDADD=''
MOD_CASE_FILTER_LDADD=''
MOD_CERN_META_LDADD=''
MOD_CGID_LDADD=''
MOD_CGI_LDADD=''
MOD_CHARSET_LITE_LDADD=''
MOD_DATA_LDADD=''
MOD_DAV_FS_LDADD=''
MOD_DAV_LDADD=''
MOD_DAV_LOCK_LDADD=''
MOD_DBD_LDADD=''
MOD_DEFLATE_LDADD=''
MOD_DIALUP_LDADD=''
MOD_DIR_LDADD=''
MOD_DUMPIO_LDADD=''
MOD_ECHO_LDADD=''
MOD_ENV_LDADD=''
MOD_EXAMPLE_HOOKS_LDADD=''
MOD_EXAMPLE_IPC_LDADD=''
MOD_EXPIRES_LDADD=''
MOD_EXT_FILTER_LDADD=''
MOD_FILE_CACHE_LDADD=''
MOD_FILTER_LDADD=''
MOD_HEADERS_LDADD=''
MOD_HEARTBEAT_LDADD=''
MOD_HEARTMONITOR_LDADD=''
MOD_HTTP_LDADD=''
MOD_IDENT_LDADD=''
MOD_IMAGEMAP_LDADD=''
MOD_INCLUDE_LDADD=''
MOD_INFO_LDADD=''
MOD_ISAPI_LDADD=''
MOD_LBMETHOD_BYBUSYNESS_LDADD=''
MOD_LBMETHOD_BYREQUESTS_LDADD=''
MOD_LBMETHOD_BYTRAFFIC_LDADD=''
MOD_LBMETHOD_HEARTBEAT_LDADD=''
MOD_LDAP_LDADD=''
MOD_LOGIO_LDADD=''
MOD_LOG_CONFIG_LDADD=''
MOD_LOG_DEBUG_LDADD=''
MOD_LOG_FORENSIC_LDADD=''
MOD_LUA_LDADD=''
MOD_MACRO_LDADD=''
MOD_MIME_LDADD=''
MOD_MIME_MAGIC_LDADD=''
MOD_MPM_EVENT_LDADD=''
MOD_NEGOTIATION_LDADD=''
MOD_OPTIONAL_FN_EXPORT_LDADD=''
MOD_OPTIONAL_FN_IMPORT_LDADD=''
MOD_OPTIONAL_HOOK_EXPORT_LDADD=''
MOD_OPTIONAL_HOOK_IMPORT_LDADD=''
MOD_PRIVILEGES_LDADD=''
MOD_PROXY_AJP_LDADD=''
MOD_PROXY_BALANCER_LDADD=''
MOD_PROXY_CONNECT_LDADD=''
MOD_PROXY_EXPRESS_LDADD=''
MOD_PROXY_FCGI_LDADD=''
MOD_PROXY_FDPASS_LDADD=''
MOD_PROXY_FTP_LDADD=''
MOD_PROXY_HTML_LDADD=''
MOD_PROXY_HTTP_LDADD=''
MOD_PROXY_LDADD=''
MOD_PROXY_SCGI_LDADD=''
MOD_PROXY_WSTUNNEL_LDADD=''
MOD_RATELIMIT_LDADD=''
MOD_REFLECTOR_LDADD=''
MOD_REMOTEIP_LDADD=''
MOD_REQTIMEOUT_LDADD=''
MOD_REQUEST_LDADD=''
MOD_REWRITE_LDADD=''
MOD_SED_LDADD=''
MOD_SESSION_COOKIE_LDADD=''
MOD_SESSION_CRYPTO_LDADD=''
MOD_SESSION_DBD_LDADD=''
MOD_SESSION_LDADD=''
MOD_SETENVIF_LDADD=''
MOD_SLOTMEM_PLAIN_LDADD=''
MOD_SLOTMEM_SHM_LDADD=''
MOD_SOCACHE_DBM_LDADD=''
MOD_SOCACHE_DC_LDADD=''
MOD_SOCACHE_MEMCACHE_LDADD=''
MOD_SOCACHE_SHMCB_LDADD=''
MOD_SO_ENABLED=''
MOD_SO_LDADD=''
MOD_SPELING_LDADD=''
MOD_SSL_LDADD=''
MOD_STATUS_LDADD=''
MOD_SUBSTITUTE_LDADD=''
MOD_SUEXEC_LDADD=''
MOD_UNIQUE_ID_LDADD=''
MOD_UNIXD_LDADD=''
MOD_USERDIR_LDADD=''
MOD_USERTRACK_LDADD=''
MOD_VERSION_LDADD=''
MOD_VHOST_ALIAS_LDADD=''
MOD_WATCHDOG_LDADD=''
MOD_XML2ENC_LDADD=''
MPM_LIB=''
MPM_SUBDIRS=''
NONPORTABLE_SUPPORT=''
NOTEST_CFLAGS=''
NOTEST_CPPFLAGS=''
NOTEST_CXXFLAGS=''
NOTEST_LDFLAGS=''
NOTEST_LIBS=''
OBJEXT=''
OS=''
OS_DIR=''
OS_SPECIFIC_VARS=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
PCRE_CONFIG=''
PCRE_LIBS=''
PICFLAGS=''
PILDFLAGS=''
PKGCONFIG=''
PORT=''
POST_SHARED_CMDS=''
PRE_SHARED_CMDS=''
RANLIB=''
RM=''
RSYNC=''
SHELL='/bin/bash'
SHLIBPATH_VAR=''
SHLTCFLAGS=''
SH_LDFLAGS=''
SH_LIBS=''
SH_LIBTOOL=''
SSLPORT=''
UTIL_LDFLAGS=''
ab_CFLAGS=''
ab_LDFLAGS=''
ab_LTFLAGS=''
abs_srcdir='/home/bcko/Downloads/httpd-2.4.12'
ac_ct_CC=''
ap_make_delimiter=''
ap_make_include=''
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
cgidir='${datadir}/cgi-bin'
checkgid_LTFLAGS=''
datadir='${prefix}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
errordir='${datadir}/error'
exec_prefix='${prefix}'
exp_bindir='/usr/local/apache2/bin'
exp_cgidir='/usr/local/apache2/cgi-bin'
exp_datadir='/usr/local/apache2'
exp_errordir='/usr/local/apache2/error'
exp_exec_prefix='/usr/local/apache2'
exp_htdocsdir='/usr/local/apache2/htdocs'
exp_iconsdir='/usr/local/apache2/icons'
exp_includedir='/usr/local/apache2/include'
exp_installbuilddir='/usr/local/apache2/build'
exp_libdir='/usr/local/apache2/lib'
exp_libexecdir='/usr/local/apache2/modules'
exp_localstatedir='/usr/local/apache2'
exp_logfiledir='/usr/local/apache2/logs'
exp_mandir='/usr/local/apache2/man'
exp_manualdir='/usr/local/apache2/manual'
exp_proxycachedir='/usr/local/apache2/proxy'
exp_runtimedir='/usr/local/apache2/logs'
exp_sbindir='/usr/local/apache2/bin'
exp_sysconfdir='/usr/local/apache2/conf'
fcgistarter_LTFLAGS=''
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htcacheclean_LTFLAGS=''
htdbm_LTFLAGS=''
htdigest_LTFLAGS=''
htdocsdir='${datadir}/htdocs'
htmldir='${docdir}'
htpasswd_LTFLAGS=''
httxt2dbm_LTFLAGS=''
iconsdir='${datadir}/icons'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
installbuilddir='${datadir}/build'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/modules'
localedir='${datarootdir}/locale'
localstatedir='${prefix}'
logfiledir='${localstatedir}/logs'
logresolve_LTFLAGS=''
mandir='${prefix}/man'
manualdir='${datadir}/manual'
oldincludedir='/usr/include'
other_targets=''
pdfdir='${docdir}'
perlbin=''
prefix='/usr/local/apache2'
progname=''
program_transform_name='s,x,x,'
proxycachedir='${localstatedir}/proxy'
psdir='${docdir}'
rel_bindir='bin'
rel_cgidir='cgi-bin'
rel_datadir=''
rel_errordir='error'
rel_exec_prefix=''
rel_htdocsdir='htdocs'
rel_iconsdir='icons'
rel_includedir='include'
rel_installbuilddir='build'
rel_libdir='lib'
rel_libexecdir='modules'
rel_localstatedir=''
rel_logfiledir='logs'
rel_mandir='man'
rel_manualdir='manual'
rel_proxycachedir='proxy'
rel_runtimedir='logs'
rel_sbindir='bin'
rel_sysconfdir='conf'
rotatelogs_LTFLAGS=''
runtimedir='${localstatedir}/logs'
sbindir='${exec_prefix}/bin'
shared_build=''
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/conf'
target='x86_64-unknown-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='unknown'

configure: exit 1

**Comment by ianamason** [comment]
# Compiling Apache on Ubuntu


On a clean 14.04 machine I will build apache.

```
> pwd

/vagrant

>more /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
```


## Step 0.

Checkout the wllvm repository

```
>git clone https://github.com/SRI-CSL/whole-program-llvm.git
```

## Step 1.

Set up the environment 

```
>export WLLVM_HOME=/vagrant/whole-program-llvm

>export PATH=${WLLVM_HOME}:${PATH}

>which wllvm

/vagrant/whole-program-llvm/wllvm
```

## Step 2.

I am only going to build apache, not apr, so I first install the prerequisites.

```
>sudo apt-get update

>sudo apt-get install llvm-3.4 clang-3.4 libapr1-dev libaprutil1-dev

>sudo ln -s /usr/bin/llvm-link-3.4 /usr/bin/llvm-link
```
This last step is an ugly hack to get

```
>which llvm-link
/usr/bin/llvm-link
```

## Step 3.

  Configure the wllvm tool to use clang and be relatively quiet:

```
>export LLVM_COMPILER=clang
>export WLLVM_OUTPUT=WARNING
```

## Step 4.

 Fetch apache, untar, configure, then build:

```
>wget http://apache.mirrors.pair.com//httpd/httpd-2.4.12.tar.gz

>tar xfz httpd-2.4.12.tar.gz

>cd httpd-2.4.12

>CC=wllvm ./configure

>extract-bc httpd

>ls -la httpd.bc
-rw-r--r-- 1 vagrant vagrant 829960 Jun  1  2015 httpd.bc
```

**Comment by ianamason** [comment]
P.S. bcko.

If you want me to diagnose what you are doing wrong, you'll need to show me the config.log

**Comment by bcko** [comment]
Dear @ianamason,

What a detailed instruction. I am installing a fresh ubuntu 14.04 right now, and going to follow your instruction step by step.
I will let you know if I succeed. 
Thank you so much!

**Comment by bcko** [comment]
Dear @ianamason,

I had some issues when I tried extract-bc httpd. I realized that I forgot to call make after CC=wllvm ./configure. After putting make in between CC=wllvm ./configure and extract-bc httpd, I was able to successfully make a bitcode!
I think many people like me can benefit from your explanation.  Thank you so much!

**Comment by ianamason** [comment]
Right . I left out the all important make. Sorry.

The tutorial, such as it is, now lives [here.](https://github.com/SRI-CSL/whole-program-llvm/blob/master/tutorial.md)

I removed the need for the llvm-link hack to.

**Comment by bcko** [comment]
I checked the tutorial, and it looks more organized.
I am also going to try your BSD tutorial as well! 
Thank you so much again.
