### ISSUE TITLE
fail to build binutils with wllvm

### ISSUE THREAD

**Issue by xiedingbao** [travitch/whole-program-llvm#31]
I attempted to build  binutils (version 2.25) with wllvm, but got and configuration error.
wllvm gave a warning: Did not recognize the compiler flag "-print-prog-name=ld".
After  disabling the output of this warning, it works.  
I think we should modify defaultArgPatterns to match the compiler flag?

**Comment by ianamason** [comment]
So it does.

What a strange compiler flag.

And adding it does fix it....
