### ISSUE TITLE
Finding mapping between llvm and native instructions

### ISSUE THREAD

**Issue by riyadparvez** [travitch/whole-program-llvm#32]
This may be a very stupid question. I guess it's not doable easily.

Is there a way to find mapping between llvm instructions (storing the corresponding native instruction in debug metadata in llvm IR) and native instructions by modifying current wllvm? Any pointer will be appreciated.

**Comment by ianamason** [comment]
I don't think this has much to do with wllvm, which apart from book keeping, is just a thin wrapper
around the compiler.  If the following is useful

http://llvm.org/docs/SourceLevelDebugging.html

then I think just experimenting with compiler flags might be a good way to start. Note that apart
from research tools like mcsema. The only thing LLVM IR knows about it is where it came from
(i.e. C or ...), not where it is going ...
