### ISSUE TITLE
Didn't recognize link step

### ISSUE THREAD

**Issue by pgoodman** [travitch/whole-program-llvm#33]
Below is the debug info for the link step of building the code. All prior steps created hidden `.bc` files for the object files, but this last step seems to have missed the fact that it should be linking the bitcode files associated with the object files into the final executable.

```/home/pag/Code/fslice/whole-program-llvm/wllvm -o testfs -g -Wall -DDISABLE_RECON -DDISABLE_PROMPT -DDISABLE_OSYNC -DDISABLE_PROLOG  testfs.o bitmap.o block.o super.o inode.o dir.o file.o tx.o common.o -lpopt 
INFO::utils.getBuilder() at utils.py:601 ::WLLVM compiler using clang
INFO::utils.getBuilder() at utils.py:603 ::WLLVM compiler path prefix "/home/pag/Code/fslice/llvm/build/bin/"
DEBUG::popenwrapper.Popen() at popenwrapper.py:13 ::WLLVM Executing:
['/home/pag/Code/fslice/llvm/build/bin/clang',
 '-o',
 'testfs',
 '-g',
 '-Wall',
 '-DDISABLE_RECON',
 '-DDISABLE_PROMPT',
 '-DDISABLE_OSYNC',
 '-DDISABLE_PROLOG',
 'testfs.o',
 'bitmap.o',
 'block.o',
 'super.o',
 'inode.o',
 'dir.o',
 'file.o',
 'tx.o',
 'common.o',
 '-lpopt']
in: /home/pag/Code/testfs/no-recon
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item -o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item -g
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item -Wall
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item -DDISABLE_RECON
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item -DDISABLE_PROMPT
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item -DDISABLE_OSYNC
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item -DDISABLE_PROLOG
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item testfs.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item bitmap.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item block.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item super.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item inode.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item dir.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item file.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item tx.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item common.o
DEBUG::utils.__init__() at utils.py:263 ::Trying to match item -lpopt
DEBUG::utils.buildAndAttachBitcode() at utils.py:637 ::No work to do
DEBUG::utils.buildAndAttachBitcode() at utils.py:638 ::{'isAssembleOnly': False, 'objectFiles': ['testfs.o', 'bitmap.o', 'block.o', 'super.o', 'inode.o', 'dir.o', 'file.o', 'tx.o', 'common.o'], 'isVerbose': False, 'isCompileOnly': False, '_inputArgs': deque([]), 'outputFilename': 'testfs', 'compileArgs': ['-g', '-Wall', '-DDISABLE_RECON', '-DDISABLE_PROMPT', '-DDISABLE_OSYNC', '-DDISABLE_PROLOG'], 'isDependencyOnly': False, 'isAssembly': False, 'linkArgs': ['-lpopt'], 'isPreprocessOnly': False, 'inputFiles': []}
```

**Comment by ianamason** [comment]
I'd be happy to debug this but I need more to go on. Can you package it up and point me to it?

**Comment by ianamason** [comment]
does the compile produce the executable  testfs?
if so what does 

extract-bc testfs 


say?

**Comment by pgoodman** [comment]
It produces the testfs executable which can be run directly. Running extract-bc reports an invalid record for .bitmap.o.bc‎, where bitmap.o is one of several object files used in the link process.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Ian A MasonSent: Thursday, September 10, 2015 6:58 PMTo: travitch/whole-program-llvmReply To: travitch/whole-program-llvmCc: Peter GoodmanSubject: Re: [whole-program-llvm] Didn't recognize link step (#33)does the compile produce the executable  testfs?
if so what does 

extract-bc testfs 

say?

—Reply to this email directly or view it on GitHub.

**Comment by ianamason** [comment]
Can I see the error report?

**Comment by pgoodman** [comment]
I am dumb! I just realized that I was building with the right env vars, but not extracting with them ;-)

**Comment by ianamason** [comment]
It pretty easy to screw up. The SRI fork has a cmd line tool that does a quick sanity check.
