### ISSUE TITLE
how to extract bitcode for postgresql

### ISSUE THREAD

**Issue by wangk7** [travitch/whole-program-llvm#37]
Hi,

I tried to extract bitcode for httpd. I do "extract-bc httpd" after it is built, and it works perfectly.
Now I'm trying to extract bitcode for postgresql. But the problem is that I don't know what should I extract?

Any suggestions? Thank you.

**Comment by travitch** [comment]
I'm not sure how postgres is structured, but you'll probably want to extract from the postgres or postmaster binaries. It depends what you are looking for. Those two are most of the core server.

**Comment by wangk7** [comment]
Actually I want to do some whole-program analysis for large C projects, not limited to postgresql.
I want to easily extract bitcode for whole-program, like httpd.

Any large C projects worth trying? Thank you.

**Comment by travitch** [comment]
It really depends on what you want to look for.Bind is big and messy. vim could be interesting. Maybe openssh.
