### ISSUE TITLE
Some unrecognized flags as of May 26, 2016

### ISSUE THREAD

**Issue by mdimjasevic** [travitch/whole-program-llvm#39]
Here are a few flags I ran into that WLLVM didn't recognize:

```
WARNING:Did not recognize the compiler flag "-pedantic"
WARNING:Did not recognize the compiler flag "-print-prog-name=ld"
WARNING:Did not recognize the compiler flag "-pie"
WARNING:Did not recognize the compiler flag "--shared"
WARNING:Did not recognize the compiler flag "debian/libcolord2/usr/lib/x86_64-linux-gnu/libcolord.so.2"
WARNING:Did not recognize the compiler flag "debian/libcolord2/usr/lib/x86_64-linux-gnu/libcolordprivate.so.2"
WARNING:Did not recognize the compiler flag "debian/libcolorhug2/usr/lib/x86_64-linux-gnu/libcolorhug.so.2"
```

If you need more info for the "debian" flags, just let me know.

**Comment by ianamason** [comment]
The - style flags are not that important. The .so.N are important. I fixed the .so (but not the .so.N)
in SRI's fork. I will also fix the .so.N is SRI's fork.

**Comment by ianamason** [comment]
We (@BrunoDutertre and I) did the port to the mac. We use it on both mac and linux most weeks.
Like last week I did gmp, yices, and libpoly using it.  

I doubt that I will push up again since my last push is still sitting there getting lonely. My guess
is Tristan doesn't use the mac version so doesn't care that his version is broken.

**Comment by mdimjasevic** [comment]
@travitch, @ianamason fixed this issue in a fork and explained in a discussion related to his commit why the fork: https://github.com/SRI-CSL/whole-program-llvm/commit/17f2e850defb10f2a0eb3263041e618793125870#commitcomment-17641358

Would you consider cherry-picking that commit and putting it here upstream?

Even better, would you guys consider merging the repos? I'm sure everyone involved would benefit from it.
