### ISSUE TITLE
Error opening output file '/dev/.null.bc': Permission denied

### ISSUE THREAD

**Issue by mdimjasevic** [travitch/whole-program-llvm#41]
Dear WLLVM devs,

I tried to use WLLVM to compile a Debian source package for [musl](https://sources.debian.net/src/musl/1.1.5-2/) to LLVM bitcode, but I get this error:

```
checking for C compiler... wllvm
checking whether C compiler works... no; compiler output follows:
error: unable to open output file '/dev/.null.bc': 'Error opening output file '/dev/.null.bc': Permission denied'
```

Do you have any clue why this is happening? If you are interested, I'm attaching a full build log file. 
[musl-build-cow.txt](https://github.com/travitch/whole-program-llvm/files/333970/musl-build-cow.txt)

Note I've been able to build about 1000 Debian source packages with WLLM so far.

This was with clang 3.4.2.

**Comment by ianamason** [comment]
There is an environment variable for configure only. See the README. Maybe this is what you need to use.

**Comment by ianamason** [comment]
We build Musl  all the time. We even have a fork @ sri-csl. It is not unusual to have to use the configure only flag when configuring. We create files that the configure script can't rip on.
The flag prevents that.

**Comment by mdimjasevic** [comment]
@ianamason, thanks!

So, you pass the WLLVM_CONFIGURE_ONLY=1 variable when calling musl's configure script like this:

```bash
WLLVM_CONFIGURE_ONLY=1 ./configure ...
```

but then later on you don't use the variable? Can you please c/p the steps you make? I've been trying to automate this within a Debian package build system, but it ends in this:

```
./tools/install.sh -D -m 644 include/wctype.h /tmp/buildd/musl-1.1.5/debian/tmp/usr/include/x86_64-linux-musl/wctype.h
./tools/install.sh -D -m 644 include/wordexp.h /tmp/buildd/musl-1.1.5/debian/tmp/usr/include/x86_64-linux-musl/wordexp.h
make[1]: Leaving directory '/tmp/buildd/musl-1.1.5'
   dh_install -O--parallel
WARNING:Did not recognize the compiler flag "-dumpmachine"
dh_install: musl-tools missing files (usr/bin/*), aborting
debian/rules:49: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
E: Failed autobuilding of package
```

**Comment by ianamason** [comment]
Correct. We do:

```
WLLVM_CONFIGURE_ONLY=1  CC=wllvm ./configure 
make
```

I rarely do installs, so not sure what the last error is about.  See if you can figure out the exact
line that is failing.

**Comment by ianamason** [comment]
Closeable?

**Comment by mdimjasevic** [comment]
@ianamason, yes, closeable. Thank you for the clarification!
