### ISSUE TITLE
some symbols undefined after extract-bc (llvmlinux) 

### ISSUE THREAD

**Issue by ziqiaozhou** [travitch/whole-program-llvm#42]
I compiled llvmlinux(git://git.linuxfoundation.org/llvmlinux/kernel.git) successfully using wllvm, and extract-bc vmlinux.o to vmlinux.o.bc. However I found lots of symbols undefined in vmlinux.o.bc compared with vmlinux.o. for example, 
llvm-nm vmlinux.o.bc | grep  x86_platform_ipi:                   U x86_platform_ipi
llvm-nm vmlinux.o | grep  x86_platform_ipi:                        00000ff0 T x86_platform_ipi

Is this a bug in wllvm or extract-bc?

**Comment by ianamason** [comment]
No it is a result of some things being defined in assembly.
the bc only contains those definitions that originate from compiled
C or C++ code. to use the the bc you would eventually have to
link against something with the missing symbols. There is not
much wllvm can do to help here, except perhaps keep track of the 
asm files used and the object files they generate. this is on my todo list.

**Comment by ianamason** [comment]
Can I close this?
