### ISSUE TITLE
configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by qingkunM** [travitch/whole-program-llvm#45]
I have recently build grep-2.18 bitcode from source code using wllvm, however failed in the configure step. The terminal says "configure: error: C compiler cannot create executables". Here is my build instructions and config.log hoping anyone can give some suggestions. Thank you.
instcution( I have already export LLVM_COMPILER as clang and the llvm clang version is 3.4):

CC=wllvm LLVM_LINK_NAME=llvm-link LLVM_AR_NAME=llvm-ar WLLVM_CONFIGURE_ONLY=1 ../configure --disable-nls CFLAGS="-g"

Here is the key error log:
## ----------- ##

configure:3374: checking for a BSD-compatible install
configure:3446: result: /usr/bin/install -c
configure:3457: checking whether build environment is sane
configure:3512: result: yes
configure:3671: checking for a thread-safe mkdir -p
configure:3714: result: /bin/mkdir -p
configure:3721: checking for gawk
configure:3755: result: no
configure:3721: checking for mawk
configure:3741: found /usr/bin/mawk
configure:3752: result: mawk
configure:3763: checking whether make sets $(MAKE)
configure:3785: result: yes
configure:3805: checking whether make supports nested variables
configure:3822: result: yes
configure:3953: checking whether make supports nested variables
configure:3970: result: yes
configure:3989: checking build system type
configure:4003: result: x86_64-unknown-linux-gnu
configure:4023: checking host system type
configure:4036: result: x86_64-unknown-linux-gnu
configure:4060: checking for gawk
configure:4091: result: mawk
configure:4155: checking for gcc
configure:4186: result: wllvm
configure:4431: checking for C compiler version
configure:4440: wllvm --version >&5
../configure: 1: eval: wllvm: not found
configure:4451: $? = 127
configure:4440: wllvm -v >&5
../configure: 1: eval: wllvm: not found
configure:4451: $? = 127
configure:4440: wllvm -V >&5
../configure: 1: eval: wllvm: not found
configure:4451: $? = 127
configure:4440: wllvm -qversion >&5
../configure: 1: eval: wllvm: not found
configure:4451: $? = 127
configure:4440: wllvm -version >&5
../configure: 1: eval: wllvm: not found
configure:4451: $? = 127
configure:4471: checking whether the C compiler works
configure:4493: wllvm -g   conftest.c  >&5
../configure: 1: eval: wllvm: not found
configure:4497: $? = 127
configure:4535: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU grep"
| #define PACKAGE_TARNAME "grep"
| #define PACKAGE_VERSION "2.18"
| #define PACKAGE_STRING "GNU grep 2.18"
| #define PACKAGE_BUGREPORT "bug-grep@gnu.org"
| #define PACKAGE_URL "http://www.gnu.org/software/grep/"
| #define GREP 1
| #define PACKAGE "grep"
| #define VERSION "2.18"
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:4540: error: in `/home/mqk/grep-2.18/build':
configure:4543: error: C compiler cannot create executables
See `config.log' for more details

**Comment by qingkunM** [comment]
To exclude all other environment's effect, I install a new virtual machine only building llvm-3.4 and clang-3.4. My system version is Ubuntu14.04.3 LTS. Any suggestion will be appreciated!

**Comment by ianamason** [comment]
I see "eval:  wllvm: not found" in the logs. Is it in your path?

**Comment by qingkunM** [comment]
Yes, you are right. I am so careless! No wonder when I replace wllvm with the absolute path it is just fine. Thank you very much!
