### ISSUE TITLE
configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by pfsun** [travitch/whole-program-llvm#46]
Hi,

I just follow the example to compile pkg-config. I meet the following problem. How could I solve the problem?  Thanks.

whole-program-llvm/test/pkg-config-0.29.1$ CC=wllvm ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... wllvm
checking whether the C compiler works... no
configure: error: in `/home/sun/project/whole-program-llvm/test/pkg-config-0.29.1':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by travitch** [comment]
Have you set the `LLVM_COMPILER` environment variable?  What do you see in config.log?

**Comment by pfsun** [comment]
Yea. I set LLVM_COMPILER. The config.log is as follows:
configure:3434: wllvm --version >&5
CRITICAL:LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
Traceback (most recent call last):
  File "/home/sun/project/whole-program-llvm/wllvm", line 18, in <module>
    builder = getBuilder(cmd, False)
  File "/home/sun/project/whole-program-llvm/driver/utils.py", line 645, in getBuilder
    raise Exception(errorMsg)
Exception: LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
configure:3445: $? = 1
configure:3434: wllvm -v >&5
CRITICAL:LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
Traceback (most recent call last):
  File "/home/sun/project/whole-program-llvm/wllvm", line 18, in <module>
    builder = getBuilder(cmd, False)
  File "/home/sun/project/whole-program-llvm/driver/utils.py", line 645, in getBuilder
    raise Exception(errorMsg)
Exception: LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
configure:3445: $? = 1
configure:3434: wllvm -V >&5
CRITICAL:LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
Traceback (most recent call last):
  File "/home/sun/project/whole-program-llvm/wllvm", line 18, in <module>
    builder = getBuilder(cmd, False)
  File "/home/sun/project/whole-program-llvm/driver/utils.py", line 645, in getBuilder
    raise Exception(errorMsg)
Exception: LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
configure:3445: $? = 1
configure:3434: wllvm -qversion >&5
CRITICAL:LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
Traceback (most recent call last):
  File "/home/sun/project/whole-program-llvm/wllvm", line 18, in <module>
    builder = getBuilder(cmd, False)
  File "/home/sun/project/whole-program-llvm/driver/utils.py", line 645, in getBuilder
    raise Exception(errorMsg)
Exception: LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
configure:3445: $? = 1
configure:3465: checking whether the C compiler works
configure:3487: wllvm    conftest.c  >&5
CRITICAL:LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
Traceback (most recent call last):
  File "/home/sun/project/whole-program-llvm/wllvm", line 18, in <module>
    builder = getBuilder(cmd, False)
  File "/home/sun/project/whole-program-llvm/driver/utils.py", line 645, in getBuilder
    raise Exception(errorMsg)
Exception: LLVM_COMPILER=/home/sun/project/LLVM/build/bin/clang : Invalid compiler type
configure:3491: $? = 1
configure:3529: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "pkg-config"
| #define PACKAGE_TARNAME "pkg-config"
| #define PACKAGE_VERSION "0.29.1"
| #define PACKAGE_STRING "pkg-config 0.29.1"
| #define PACKAGE_BUGREPORT "https://bugs.freedesktop.org/enter_bug.cgi?product=pkg-config"
| #define PACKAGE_URL ""
| #define PACKAGE "pkg-config"
| #define VERSION "0.29.1"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3534: error: in `/home/sun/project/whole-program-llvm/test/pkg-config-0.29.1':
configure:3536: error: C compiler cannot create executables
See `config.log' for more details

**Comment by travitch** [comment]
You need to set `LLVM_COMPILER` to the string `clang` or `dragonegg`, not the path to the executable.

**Comment by pfsun** [comment]
Got it. I set LLVM_COMPILER to the string clang. Now I can configure correctly without the same error.  Thanks a lot :-)
