### ISSUE TITLE
clang-3.4: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by qingkunM** [travitch/whole-program-llvm#48]
Hello, when i compile pkg-config-0.18.1 the following problem comes up. It denotes something wrong with the linker command. Does anyone know the problem? Thank you very much.

/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gtree.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gtree.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gtree.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(ghash.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(ghash.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(ghash.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(garray.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(garray.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(garray.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(glist.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(glist.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(glist.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gslist.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gslist.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gslist.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testgdate.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gmem.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gmem.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gmem.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gmessages.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gmessages.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gmessages.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gmutex.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gmutex.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gmutex.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gnode.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gnode.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gnode.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gprimes.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gprimes.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gprimes.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(grel.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(grel.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(grel.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gslist.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gslist.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gslist.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gstrfuncs.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gstrfuncs.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gstrfuncs.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gstring.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gstring.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gstring.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gtimer.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gtimer.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gtimer.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gtree.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gtree.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gtree.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
./.libs/libglib.a(gutils.o): In function `g_bit_nth_lsf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: multiple definition of `g_bit_nth_lsf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1563: first defined here
./.libs/libglib.a(gutils.o): In function `g_bit_nth_msf':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: multiple definition of `g_bit_nth_msf'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1578: first defined here
./.libs/libglib.a(gutils.o): In function `g_bit_storage':
/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: multiple definition of `g_bit_storage'
testglib.o:/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8/./glib.h:1596: first defined here
clang-3.4: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [testgdateparser] Error 1
make[4]: *** Waiting for unfinished jobs....
clang-3.4: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [testgdate] Error 1
clang-3.4: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [testglib] Error 1
make[4]: Leaving directory `/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/mqk/Downloads/pkg-config-0.18.1/glib-1.2.8'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/mqk/Downloads/pkg-config-0.18.1'
make: *** [all] Error 2

**Comment by qingkunM** [comment]
I am using clang-3.4 and llvm-3.4(build from source instead of pre-binary).  Building pkg-config-0.18.1 through gcc just woks well. Hoping for your advices @travitch @ianamason.

**Comment by delcypher** [comment]
@qingkunM Have you checked that building pkg-config with clang-3.4 actually works? IIRC whole-program doesn't invoke the linker directly so I would expect to the see the same error message above when building with clang-3.4

**Comment by qingkunM** [comment]
@delcypher How to build pkg-config with clang-3.4? Just type CC=clang ./configure; make?
I have tried the above command which is no good. The log is just like  pasted at first. I have googled the problem that  pkg-config-0.18.1 contains glibc but clang-3.4 references it again.

**Comment by ianamason** [comment]
I'm offline so cannot say more than what Daniel has already said. Make sure you can build it with your clang without wllvm involved.  If you can then it should also build with wllvm. I'm back online next week.

**Comment by qingkunM** [comment]
@delcypher @ianamason Ok, I get your ideas.
