### ISSUE TITLE
Pip?

### ISSUE THREAD

**Issue by ianamason** [travitch/whole-program-llvm#51]
Tristan,

Do you want me to push my pipification of wllvm upstream? The changes
are mostly structural, but rather pervasive, the dragonegg 'as' was the trickiest.  
Take a look and let me know what you think.

https://github.com/SRI-CSL/whole-program-llvm

It is up to date  otherwise, but may be a messy pull request due
to the structural changes.

Cheers, Ian.

**Comment by travitch** [comment]
Yes, please do.  I don't mind the churn for a good cause.

**Comment by ianamason** [comment]
Done.
