### ISSUE TITLE
-emit-llvm

### ISSUE THREAD

**Issue by relentless-warrior** [travitch/whole-program-llvm#55]
Hi,

I was trying to build android-6.0.1_r60 with wllvm and I ran into the following issues:

`WARNING:Out of context experience: "['-Iframeworks/rs/scriptc', '-Iexternal/clang/lib/Headers', '-MD', '-DRS_VERSION=23', '-std=c99', '-c', '-O3', '-fno-builtin', '-emit-llvm', '-target', 'armv7-none-linux-gnueabi', '-fsigned-char', '-D__i386__', '-Iframeworks/rs/cpu_ref', '-DRS_DECLARE_EXPIRED_APIS', '-Xclang', '-fnative-half-type', '-Xclang', '-fallow-half-arguments-and-returns', '-Xclang', '-target-feature', '-Xclang', '+long64', 'frameworks/rs/driver/runtime/rs_allocation.c', '-o', 'out/target/product/generic_x86/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/rs_allocation.bc']" "-emit-llvm"
`
I have found that if the argument list has -emit-llvm, wllvm calls abortUnaryCallback which actually issues this error message and exit from the build.

```
class ArgumentListFilter(object):
    ...
    #iam: if this happens, then we need to stop and think.
    '-emit-llvm' : (0, ArgumentListFilter.abortUnaryCallback),
```

Is there any fix for that?

**Comment by ianamason** [comment]
Yes it poses a bit of a conundrum. Since there is no object file associated with the bit code product
`rs_allocation.bc`, we have no way to move forward.  Something may be possible, but I do not see it.

@travitch  @delcypher  @BrunoDutertre  any ideas?

**Comment by ianamason** [comment]
After talking a bit with @BrunoDutertre , perhaps just not aborting might be interesting.
So just change the abortUnaryCallback to a compileUnaryCallback, though printing an obvious warning might help.

Who knows what will happen in the  build process. But there is only one way to find out.

At some stage I would guess that the .bc file will get turned into a .o  (but it could also be more complex than this) . If it does just get turned into a .o then we could probably catch it at that point
and embed the path into the .o file.  Anyway I would be willing to work with you to see if we could 
do something like that.

**Comment by travitch** [comment]
Trying to catch the .bc->.o conversion is really interesting.  It makes sense.  Do we know what this part of the build system is trying to accomplish?  I assume it will create a .o eventually, but I'm unclear on why it goes through bitcode here.

**Comment by ianamason** [comment]
Yes that is my worry, there could be all sorts of hanky panky going on. But
my hope is that we could disregard that. As long as the hanky panky just involves
building more .bc files. All we really need to do it catch the final product at the time
it gets turned into a .o (or make up one if it gets used in a linking step, but we already catch
cases like that so...).

**Comment by relentless-warrior** [comment]
After changing to compileUnaryCallback, the build ended with success. However, I've got warning messages like this:

`WARNING:Cannot attach bitcode path to "out/target/product/generic_x86/obj/SHARED_LIBRARIES/libclcore_debug.bc_intermediates/rs_sampler.bc of type 0"`

I actually built the Bluetooth module only of android-6.0.1_r60. The build generated libbluetooth_jni.so file. I have then tried with extract-bc script to retrieve the bitcode. But, it did not find the llvm_bc section there.

I haven't yet tried @ianamason's suggestion. I will keep you updated about this.

**Comment by ianamason** [comment]
Yeah the warnings make sense since the code expects the generated stuff is either an 
object or an executable. why there is no segment in the .so is more surprising. how big is the
log of the build? hours minutes or seconds? If it is not too huge you could put it somewhere.
I may try to do a simple experiment with the SRI fork in the next few days, to see if the ideas mentioned above can be made to pan out.

**Comment by relentless-warrior** [comment]
@ianamason: The log of the Bluetooth build is about 20 minutes. I will post it somewhere and share the link with you.

**Comment by relentless-warrior** [comment]
Here goes the link of the build's log:
https://www.dropbox.com/s/54ufz9hrmw7uqnc/android-6.0.1_r60-bluetooth-build.txt?dl=0

**Comment by ianamason** [comment]
Thanks. I'll take a look soonish. I'm seeing if I can flesh out the ideas sketched above
for some toy examples.

**Comment by ianamason** [comment]
Couple of remarks.

1. The ideas above were scary easy to implement, and have been done in the SRI fork.

https://github.com/SRI-CSL/whole-program-llvm.git

which you can try out if you are feeling brave. Once we have tested them better we can push them 
into the pip package, and upstream to @travitch's repo

2.

I took a quick grep through the logfile you put up, kind of hard to know exactly what is going on 
but  it looks like they are aggregating lots of bc files into one large one.

```
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_allocation.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_cl.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_core.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_element.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_mesh.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_matrix.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_program.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_sample.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_sampler.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/rs_convert.c
bc: libclcore.bc <= frameworks/rs/driver/runtime/arch/generic.c
```
and then doing some libish thing with the result.

```
bc lib: libclcore.bc (out/target/product/generic_x86/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/libclcore.bc)
Install: out/target/product/generic_x86/system/lib/libclcore.bc
```

if the .so is built out of these things, I am not surprised that there ain't no
segment there.

**Comment by ianamason** [comment]
The fix is in. Not tested but I guess I cannot force people to do so.
