### ISSUE TITLE
Generating bitcode for Linux kernel

### ISSUE THREAD

**Issue by AdrianGolding** [travitch/whole-program-llvm#61]
I am trying to generate LLVM bitcode for the linux kernel using wllvm. i understand there will be some extensions and some files (e.g assembly files such as kernel/bounds.s) that cannot be handled, and i'm fine to limp along with whatever bitcode that clang can work with. ideally i'll leave linux kernel sources as it is, without doing patching. 

may i know how should i run the wllvm in this case, in such a way that it'll just gracefully ignore files that it can't work with?

**Comment by ianamason** [comment]
It should work fine, it will mention missing stuff when running extract-bc but should still generate bitcode. An warm up example is musl libc. That has some assembly and compiles just fine.

**Comment by ianamason** [comment]
Also I guess you will have to use dragon egg because I don't think the kernel compiles with clang.
Not sue how upto date dragon egg is either. I know in our Travis tests it is pretty ancient. Llvm 3.4 if I remember correctly (unlikely)

**Comment by AdrianGolding** [comment]
thanks for the suggestions, i'll try it out! hope it works!

**Comment by travitch** [comment]
Compiling Linux with clang really isn't supported yet.  If you are okay with an older version of Linux, you might try http://llvm.linuxfoundation.org/index.php/Main_Page, which has some patches that might work.

**Comment by AdrianGolding** [comment]
yup, i understand. i looked at llvmlinux and a number of links are broken. not sure if it is still maintained. 
thanks for the help anyways!
