### ISSUE TITLE
Issues in compiling 483.xalancbmk 

### ISSUE THREAD

**Issue by snehasish** [travitch/whole-program-llvm#62]
My environment:
wllvm version 1.1.4 installed from pip
clang-3.8 
SPECCPU2006 1.0 wllvm config file attached
[linux64-amd64-wllvm.cfg.txt](https://github.com/travitch/whole-program-llvm/files/1216561/linux64-amd64-wllvm.cfg.txt)
SPEC build log attached
[CPU2006.016.log.txt](https://github.com/travitch/whole-program-llvm/files/1216571/CPU2006.016.log.txt)

After the build succeeds, I run
$ extract-bc Xalan && clang Xalan.bc -lstdc++ -lm 

Expected output: a.out 
Result: Undefined reference errors (attached log file)
[undefined_reference_errors.txt](https://github.com/travitch/whole-program-llvm/files/1216578/undefined_reference_errors.txt)

Additional info:
$ ldd Xalan
	linux-vdso.so.1 =>  (0x00007ffc0a922000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb54270f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb542405000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb5421ef000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb541e25000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d2615a8000)

It looks like some xerces library bitcode is missing from the final extracted bitcode.

**Comment by ianamason** [comment]
If there is any assembly anywhere you will get this sort of thing happening.

**Comment by ianamason** [comment]
But that seems unlikely. I will see if I can come up with a better explanation.
Thanks for the detailed report by the way.

**Comment by ianamason** [comment]
I cannot see any static libraries being used, so the missing xercesc and xalanc code must be just being included as header files, as C++ is want to do.  This should not cause any problems.

What does 

extract-bc Xalan

say when it is run.

**Comment by snehasish** [comment]
Running extract-bc produces no output on stdout/stderr. It produces Xalan.bc. I ran it with the -m flag and I've attached the manifest file. 

[Xalan.llvm.manifest.txt](https://github.com/travitch/whole-program-llvm/files/1216833/Xalan.llvm.manifest.txt)

For the first undefined reference error
`xercesc_2_5::BinInputStream::~BinInputStream()`

The manifest file contains
/home/ska124/Working/cpu2006/benchspec/CPU2006/483.xalancbmk/run/build_base_amd64-m64-wllvm-nn.0000/.BinInputStream.o.bc

Disassembling this to text, I see the symbol 
```
@_ZN11xercesc_2_514BinInputStreamD1Ev = alias void (%"class.xercesc_2_5::BinInputStream"*), void (%"class.xercesc_2_5::BinInputStream"*)* @_ZN11xercesc_2_514BinInputStreamD2Ev

$ c++filt _ZN11xercesc_2_514BinInputStreamD1Ev
xercesc_2_5::BinInputStream::~BinInputStream()
```

So I tried 
```
$ llvm-link Xalan.bc .BinInputStream.o.bc -o Test.bc
ERROR: Linking globals named '_ZTVN11xercesc_2_514BinInputStreamE': symbol multiply defined!
$ c++filt _ZTVN11xercesc_2_514BinInputStreamE
vtable for xercesc_2_5::BinInputStream
```

So I'm not sure how the remaining stuff was dropped while the vtable is present in the consolidated bitcode.

**Comment by ianamason** [comment]
So all `extract-bc` does is (once it has the manifest as a list) is

```
llvm-link -o Xalan <list of bitcode files in manifest>
```
so you can easily edit the manifest file to do this. The question is does `llvm-link` complain?
If it does then so should `extract-bc` (and that is a bug), if it doesn't, then this might be an example of what  @HassenSaidiatSRI has been telling me. Pity the whole thing is obscured by the prosaic build system of the spec 2006 benchmarks. Though we do have a copy here that I can dust of and take for a spin if necessary.

Can you try the hand crafted `llvm-link` command?

**Comment by snehasish** [comment]
So I checked that all the listed files were present and then tried 
`llvm-link -o Xalan.bc `cat Xalan.llvm.manifest` && clang Xalan.bc -lstdc++ -lm`
and got the same result. Is this a bug in llvm-link perhaps? I'm going to check with a newer version of llvm and see if that changes anything (I'm currently using 3.8).

**Comment by ianamason** [comment]
Certainly the issue is with `llvm-link`,  `extract-bc`  just extracts the paths from the segments, and 
calls it. But  I am not sure what the issue really is. Usually this happens just when there is assembly in the loop. Not sure why it would be an issue with straight C++. My guess is that earlier versions of `llvm-link` may be better, as far  as getting what you want.

**Comment by snehasish** [comment]
You are right, llvm-link is to blame. The issue does not appear when using the llvm-4.0 toolchain. Thanks for your time. I am closing this issue.

**Comment by ianamason** [comment]
Good to know. Thanks.
