### ISSUE TITLE
Failed to extract bitcode of Apache with APR

### ISSUE THREAD

**Issue by hungys** [travitch/whole-program-llvm#64]
The tutorial by @ianamason for compiling Apache (from https://github.com/travitch/whole-program-llvm/issues/30) just works for me. However, it assumes that Apache Portable Runtime (APR) is installed. Due to some reasons, I need to build Apache with the source of APR , but `extract-bc` fails in this scenario.

I followed the documentation of Apache by downloading the source code of [APR](https://apr.apache.org) and put it in `./srclib/` directory,

```
$ cd srclib/
$ wget http://ftp.tc.edu.tw/pub/Apache//apr/apr-1.6.2.tar.gz
$ wget http://ftp.tc.edu.tw/pub/Apache//apr/apr-util-1.6.0.tar.gz
$ tar zxvf apr-1.6.2.tar.gz
$ mv apr-1.6.2/ apr/
$ tar xzvf apr-util-1.6.0.tar.gz
$ mv apr-util-1.6.0/ apr-util/
$ cd ../
$ CC=wllvm ./configure --with-included-apr
$ make
$ extract-bc httpd
ERROR:File "/vagrant/evaluation/httpd-2.4.27/httpd" of type UNKNOWN cannot be used
```

P.S. the `httpd` binary is valid and is able to run.

**Comment by ianamason** [comment]
So you are building in a vagrant box?  What does 
```
file /vagrant/evaluation/httpd-2.4.27/httpd
```
say inside the box?  As a rule of thumb I try not to build in the shared folders of vagrant boxes
because the file system there can be a little idiosyncratic.

**Comment by aheroine** [comment]
how to solve this problem then?

**Comment by ianamason** [comment]
It is still on my in pile.
