### ISSUE TITLE
wllvm error: C compiler cannot create executables

### ISSUE THREAD

**Issue by OrenGitHub** [travitch/whole-program-llvm#67]
Hi,
I'm attaching a link to a SO question I've just posted regarding the fact that configure
complains wllvm can not create executables:

[SO-question](https://stackoverflow.com/questions/48047221/wllvm-error-c-compiler-cannot-create-executables)

What would be the best way to solve it? Thanks!
P.S.
There is no 'wllvm' label in SO, and it requires > 1500 votes to create one

**Comment by ianamason** [comment]
Try also using the configure only flag.
```
WLLVM_CONFIGURE_ONLY=1
```

It is mentioned down near the bottom of the readme.

**Comment by ianamason** [comment]
But I hope you are using clang not gcc.

**Comment by OrenGitHub** [comment]
@ianamason yes, wllvm worked fine for coreutils.
I tried running:

    CC=wllvm WLLVM_CONFIGURE_ONLY=1 ../libosip2-4.1.0/configure

But the same error repeated

**Comment by ianamason** [comment]
OK if you add a link to the source etc, I shall try this week to see what is up with it.

**Comment by OrenGitHub** [comment]
Here are the commands I'm using:

    wget https://ftp.gnu.org/gnu/osip/libosip2-4.1.0.tar.gz
    tar xf libosip2-4.1.0.tar.gz
    mkdir build
    cd build
    CC=wllvm WLLVM_CONFIGURE_ONLY=1 ../libosip2-4.1.0/configure --enable-test --disable-shared
    make -j

Prior to this I have exported LLVM_COMPILER and LLVM_COMPILER_PATH:

    export LLVM_COMPILER=/home/oren/GIT/LatestKlee/llvm/Release/bin/clang
    export LLVM_COMPILER_PATH=/home/oren/GIT/LatestKlee/llvm/Release/bin/

Here is the error message I get:

    configure: osip2                   The GNU Open SIP library.
    configure: Copyright (C) 2001-2012 Aymeric MOIZARD - <amoizard@antisip.com>
    Configuring libosip2 4.1.0
    Building Package on linux
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking for gcc... wllvm
    checking whether the C compiler works... no
    configure: error: in `/home/oren/GIT/LatestKlee/myBenchmarks/libosip_trial/build':
    configure: error: C compiler cannot create executables
    See `config.log' for more details

**Comment by OrenGitHub** [comment]
Hi,
It turns out that:

    LLVM_COMPILER=clang (works fine)

But not with an absolute path:

    LLVM_COMPILER=/home/oren/GIT/LatestKlee/llvm/Release/bin/clang (doesn't work)

Here is my final script version, **which works perfect**:

    wget https://ftp.gnu.org/gnu/osip/libosip2-4.1.0.tar.gz
    tar xf libosip2-4.1.0.tar.gz
    
    mkdir build
    cd build
    CC=wllvm LLVM_COMPILER=clang ../libosip2-4.1.0/configure --enable-test --disable-shared
    LLVM_COMPILER=clang make -j
    
    cd ./src/test
    extract-bc ./torture_test
    file ./torture_test.bc

and the desired output:

    ./torture_test.bc: LLVM IR bitcode

**Comment by ianamason** [comment]
Yes  putting a path there is a common mistake.  `wllvm-sanity-checker` would/should have picked that up. Glad it is all working fine and dandy. Not sure what our user base is, but I doubt it nears 1.5K for the votes needed for SO.
