### ISSUE TITLE
Request For Help with wllvm linking

### ISSUE THREAD

**Issue by OrenGitHub** [travitch/whole-program-llvm#68]
Hi,
**[1]** I am trying to use KLEE to check the [libosip](https://ftp.gnu.org/gnu/osip/) package.
**[2]** For that, I compiled libosip successfully* with wllvm
(* after some effort, as documented by [this (closed) issue](https://github.com/travitch/whole-program-llvm/issues/67))
**[3]** However, I need to change the libosip code, and add an external call to a
function (klee_make_symbolic) from KLEE's library.
**[4]** I've tried setting the LDFLAGS variable so it points to the location of
KLEE's libraries but with no success. Here is the script I tried:

    wget https://ftp.gnu.org/gnu/osip/libosip2-4.1.0.tar.gz
    tar xf libosip2-4.1.0.tar.gz
    
    mkdir build
    cd build
    CC=wllvm LLVM_COMPILER=clang ../libosip2-4.1.0/configure --enable-test --disable-shared LDFLAGS="-L/home/oren/GIT/LatestKlee/klee/build/lib/"
    LLVM_COMPILER=clang make -j
    
    cd ./src/test
    extract-bc ./torture_test
    file ./torture_test.bc

**[5]** Here is the linker error I get when I run make:

    /bin/bash ../../libtool --tag=CC   --mode=link wllvm -g   -pedantic -g -DENABLE_TRACE -g   -
    L/home/oren/GIT/LatestKlee/klee/build/lib/ -o torture_test torture.o   
    ../../src/osipparser2/libosipparser2.la  
    libtool: link: wllvm -g -pedantic -g -DENABLE_TRACE -g -o torture_test torture.o  -
    L/home/oren/GIT/LatestKlee/klee/build/lib/ ../../src/osipparser2/.libs/libosipparser2.a
    torture.o: In function `main':
    /home/oren/GIT/LatestKlee/myBenchmarks/libosip_bitcode_2/build/src/test/../../../libosip2-
    4.1.0/src/test/torture.c:142: undefined reference to `klee_make_symbolic'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**[6]** Any help is very much appreciated, thanks!

**Comment by ianamason** [comment]
So l do not see any use of the bitcode. Why are you using wllvm?  Is it that in step three 
you are modifying the bitcode rather than the source?  Anyway my advice would be to do 
the linking by hand. There is no need to use wllvm for linking. 
I would use clang  for the linking step.
I would also explicitly add the required klee library to the link command.

**Comment by ianamason** [comment]
@OrenGitHub   is this closable? Or do you still need help?

**Comment by OrenGitHub** [comment]
Thanks for the help @ianamason , that worked out fine, I'll close the thread.
