### ISSUE TITLE
wllvm fails with cmake

### ISSUE THREAD

**Issue by OrenGitHub** [travitch/whole-program-llvm#70]
Hi,
Recently I've successfully built many packages **with configure+make**, but now I need to build a package that ships with a **cmake build system**. Here is the script I'm using (including the ftp site of the package itself):

    #!/bin/bash
    #########
    # FILES #
    #########
    PACKAGE_NAME=openjpeg-2.3.0
    PACKAGE_TAR_FILE=${PACKAGE_NAME}.tar.gz
    PACKAGE_FTP_SITE=https://ftp.osuosl.org/pub/blfs/conglomeration/openjpeg
    
    ####################################
    # REMOVE OLD STUFF JUST TO BE SURE #
    ####################################
    rm -rf build
    rm -rf ${PACKAGE_NAME}
    rm -rf ${PACKAGE_TAR_FILE}
    
    #####################################
    # Get source code for buggy package #
    #####################################
    wget ${PACKAGE_FTP_SITE}/${PACKAGE_TAR_FILE}
    
    ######################
    # Unpack it here ... #
    ######################
    tar xf ${PACKAGE_TAR_FILE}
    
    ##########################################
    # Prepare an out of tree build directory #
    ##########################################
    mkdir build
    
    ##############################
    # Get inside build directory #
    ##############################
    cd build
    
    #################
    # Configure ... #
    #################
    CC=wllvm CXX=wllvm++ cmake -DBUILD_MJ2=On ../${PACKAGE_NAME}
    
    ###############
    # Make it !!! #
    ###############
    make -j

Here are the errors I get:

    ./myBuildingScripts/build-step0-openjpeg
    --2018-03-08 10:53:27--  https://ftp.osuosl.org/pub/blfs/conglomeration/openjpeg/openjpeg-2.3.0.tar.gz
    Resolving ftp.osuosl.org (ftp.osuosl.org)... 64.50.236.52, 140.211.166.134, 64.50.233.100, ...
    Connecting to ftp.osuosl.org (ftp.osuosl.org)|64.50.236.52|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 2207329 (2.1M) [application/x-gzip]
    Saving to: ‘openjpeg-2.3.0.tar.gz’
    
    openjpeg-2.3.0.tar.gz                        100%
    
    [======================>]   2.10M   351KB/s    in 6.5s    
    
    2018-03-08 10:53:36 (329 KB/s) - ‘openjpeg-2.3.0.tar.gz’ saved [2207329/2207329]
    
    -- The C compiler identification is unknown
    -- The CXX compiler identification is unknown
    -- Check for working C compiler: /usr/local/bin/wllvm
    -- Check for working C compiler: /usr/local/bin/wllvm -- broken
    CMake Error at /usr/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
    The C compiler "/usr/local/bin/wllvm" is not able to compile a simple test program.
    
    It fails with the following output:
    
    Change Dir: 
    /home/oren/GIT/klee/str.klee/klee/benchmarks/openjpeg_bitcode/build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_2e7d6/fast"

Any help is very much appreciated, thanks!

**Comment by ianamason** [comment]
I shall take a look tomorrow.

**Comment by ianamason** [comment]
Try using 

```
CC=wllvm CXX=wllvm++ WLLVM_CONFIGURE_ONLY=1 cmake -DBUILD_MJ2=On ../${PACKAGE_NAME}
```

**Comment by OrenGitHub** [comment]
Works perfect, thanks!
