### ISSUE TITLE
extract-bc problems with shared objects

### ISSUE THREAD

**Issue by OrenGitHub** [travitch/whole-program-llvm#71]
Hi,
I have the following script to build the libtiff package:

    #!/bin/bash
    #########
    # FILES #
    #########
    PACKAGE_NAME=tiff-3.8.2
    PACKAGE_TAR_FILE=${PACKAGE_NAME}.tar.gz
    PACKAGE_FTP_SITE=http://libtiff.maptools.org/dl
    
    ####################################
    # REMOVE OLD STUFF JUST TO BE SURE #
    ####################################
    rm -rf build
    rm -rf ${PACKAGE_NAME}
    rm -rf ${PACKAGE_TAR_FILE}
    
    #####################################
    # Get source code for buggy package #
    #####################################
    wget ${PACKAGE_FTP_SITE}/${PACKAGE_TAR_FILE}
    
    ######################
    # Unpack it here ... #
    ######################
    tar xf ${PACKAGE_TAR_FILE}
    
    ##########################################
    # Prepare an out of tree build directory #
    ##########################################
    mkdir build
    
    ##############################
    # Get inside build directory #
    ##############################
    cd build
    
    #################
    # Configure ... #
    #################
    CC=wllvm
    LLVM_COMPILER=clang
    CFLAGS="-g -O0"
    ../${PACKAGE_NAME}/configure --disable-shared
    
    ###############
    # Make it !!! #
    ###############
    make -j

Everything works fine, but then I try to extract-bc like this:

    extract-bc ./build/tools/tiffsplit

I fail with this message:

    WARNING:Could not find ".llvm_bc" ELF section in "/home/oren/GIT/klee/str.klee/klee/benchmarks/libtiff_bitcode/build/tools/tiffsplit", so skipping this entry.

The result of:

    file ./build/tools/tiffsplit

is:

    ./build/tools/tiffsplit: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, 
    BuildID[sha1]=c7c57dd98623f41270e6042d3b4b8633e343ad21, with debug_info, not stripped

What's going on here? thanks!

**Comment by ianamason** [comment]
I shall take a look tomorrow.

**Comment by OrenGitHub** [comment]
Here is another example with the same problem:

    #!/bin/bash
    #########
    # FILES #
    #########
    PACKAGE_NAME=mupdf-1.12.0-source
    PACKAGE_TAR_FILE=${PACKAGE_NAME}.tar.xz
    PACKAGE_FTP_SITE=https://mupdf.com/downloads/
    
    ####################################
    # REMOVE OLD STUFF JUST TO BE SURE #
    ####################################
    rm -rf build
    rm -rf ${PACKAGE_NAME}
    rm -rf ${PACKAGE_TAR_FILE}
    
     #####################################
     # Get source code for buggy package #
     #####################################
    wget ${PACKAGE_FTP_SITE}/${PACKAGE_TAR_FILE}
    
    ######################
    # Unpack it here ... #
    ######################
    tar xf ${PACKAGE_TAR_FILE}
    
    #################
    # Configure ... #
    #################
    cd ${PACKAGE_NAME}
    
    ###############
    # Make it !!! #
    ###############
    CC=wllvm
    LLVM_COMPILER=clang
    XCFLAGS="-g -O0"
    make debug

This is what I get when I try to extract-bc:

    extract-bc ./mupdf-1.12.0-source/build/debug/mutool

It says that it's missing some section:

    WARNING:Could not find ".llvm_bc" ELF section in "/home/oren/GIT/klee/str.klee/klee/benchmarks/mupdf_bitcode/mupdf-1.12.0-source/build/debug/mutool", so skipping this entry.

Thanks again!

**Comment by ianamason** [comment]
My cup overfloweth!  It is still on my queue.

**Comment by kren1** [comment]
I think your CC flag doesn't get exported to the shell, so it's basically ignored. 

The error is basically saying you are trying to extract from a file that isn't compiled with wllvm.

**Comment by OrenGitHub** [comment]
@kren1 thanks! I changed theses lines:

    CC=wllvm
    LLVM_COMPILER=clang
    XCFLAGS="-g -O0"

to these lines:

    export CC=wllvm
    export LLVM_COMPILER=clang
    export CFLAGS="-g -O0"

and everything is working fine !!

**Comment by ianamason** [comment]
Both are fixed?  I can close #71 ?

**Comment by OrenGitHub** [comment]
Yes, Thanks
