### ISSUE TITLE
Apache httpd cannot load dynamic libraries after building from wllvm's extracted bc

### ISSUE THREAD

**Issue by takhandipu** [travitch/whole-program-llvm#73]
I followed the apache build and rebuild from extracted bc tutorial (https://github.com/travitch/whole-program-llvm/blob/master/doc/tutorial-ubuntu-16.04.md). When I tried to start my rebuilt httpd they cannot load the dynamic libraries listed on the httpd.conf file. However, the original httpd binary (build with wllvm, but not from extracted bc) could load those modules. Is there any other way to rebuild the binary so that the binary can load these shared libraries?

**Comment by ianamason** [comment]
Interesting.  I shall look into that.

**Comment by ianamason** [comment]
Just for completeness, what does your httpd.conf look like?

**Comment by ianamason** [comment]
I haven't forgotten this. I am currently looking into it.

**Comment by takhandipu** [comment]
Thanks for going through the trouble.

**Comment by ianamason** [comment]
OK so that was instructive.  I  flipped the `WLLVM_LOG_LEVEL` to `INFO` so that I could see
the exact linking step that libtool passed to clang.
```
INFO:Entering CC [-pthread -o httpd modules.o buildmark.o -Wl,--export-dynamic server/.libs/libmain.a modules/core/.libs/libmod_so.a modules/http/.libs/libmod_http.a server/mpm/event/.libs/libevent.a os/unix/.libs/libos.a -lpcre /usr/lib/x86_64-linux-gnu/libaprutil-1.so /usr/lib/x86_64-linux-gnu/libapr-1.so -pthread]
```
futzing with this gives me:
```
clang -pthread -o httpd_from_bc httpd.bc -Wl,--export-dynamic server/.libs/libmain.a modules/core/.libs/libmod_so.a modules/http/.libs/libmod_http.a server/mpm/event/.libs/libevent.a os/unix/.libs/libos.a -lpcre /usr/lib/x86_64-linux-gnu/libaprutil-1.so /usr/lib/x86_64-linux-gnu/libapr-1.so -pthread
```
 So my guess is that the crucial incantation is the linker instruction `-Wl,--export-dynamic`

**Comment by ianamason** [comment]
Oh I forgot to mention that `httpd_from_bc` has no problems with the modules :-)

**Comment by ianamason** [comment]
Indeed, from [here](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html) we see:
```
In some cases, the call to gcc to create the object file will also need to include the option 
``-Wl,-export-dynamic''. Normally, the dynamic symbol table contains only symbols which 
are used by a dynamic object. This option (when creating an ELF file) adds all symbols to the
dynamic symbol table (see ld(1) for more information). You need to use this option when there are 
'reverse dependencies', i.e., a DL library has unresolved symbols that by convention must be 
defined in the programs that intend to load these libraries.
```

**Comment by ianamason** [comment]
Can I close this  @takhandipu ?

**Comment by takhandipu** [comment]
Yeah, you can close this. I don't have the server access at this moment therefore could not test the build configuration. Once I get the access again, I will test it. Then, if it didn't work, I will get back here. Thank you for the support though.
