### ISSUE TITLE
objcopy: src/steddNxf: failed to find link section for section 24

### ISSUE THREAD

**Issue by mewmew** [travitch/whole-program-llvm#75]
Hi,

Just wanted to check if anyone else has stumbled on this error with WLLVM? I get it when trying to build Coreutils 8.30 using LLVM 7.0 at rev 26b52aa of WLLVM.

Cheers,
Robin

```
$ wllvm --version
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
	cd coreutils-$(VER)
	export LLVM_COMPILER=clang
	CC=wllvm ./configure
	make
```

```
  CCLD     src/split
  CC       src/stat.o
objcopy: src/stkShpi9: failed to find link section for section 30
objcopy: src/stkShpi9: failed to find link section for section 30
  CCLD     src/stat
  CC       src/sum.o
objcopy: src/stuHRXtL: failed to find link section for section 24
objcopy: src/stuHRXtL: failed to find link section for section 24
  CCLD     src/sum
  CC       src/sync.o
objcopy: src/stzhYois: failed to find link section for section 23
objcopy: src/stzhYois: failed to find link section for section 23
  CCLD     src/sync
  CC       src/tac.o
objcopy: src/steddNxf: failed to find link section for section 24
objcopy: src/steddNxf: failed to find link section for section 24
  CCLD     src/tac
  CC       src/tail.o
```

**Comment by ianamason** [comment]
No. This looks new.  I will take a look soonish.

**Comment by ianamason** [comment]
Hmmm. 

It built fine for me, with both LLVM 5.0 and LLVM 7.0.
I guess I am using `wllvm` from the SRI-CSL  github account,

https://github.com/SRI-CSL/whole-program-llvm

but I don't think that should not  make any difference, since I try and keep @travitch 's version up to date.

To be honest though. I rarely use `wllvm` any more. I use `gllvm` instead. It is a drop in replacement
to `wllvm` and is way faster (though it does not support dragonegg).

https://github.com/SRI-CSL/gllvm

See if that solves your problem.

What `objcopy` are you using?

```
vagrant@ubuntu-xenial:/vagrant/coreutils-8.30$ objcopy --version
GNU objcopy (GNU Binutils for Ubuntu) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

I was building in a vagrant box:
```
vagrant@ubuntu-xenial:/vagrant/coreutils-8.30$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```

**Comment by ianamason** [comment]
One last comment (don't take this as a insult) but did you try and build without the
`CC=wllvm` and use `CC=clang` instead?*

**Comment by mewmew** [comment]
@ianamason Thanks for helping out with the troubleshooting!

I was using wllvm from https://github.com/travitch/whole-program-llvm as that is what is used in the AUR package for Arch Linux: https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=wllvm-git

However, I updated to use https://github.com/SRI-CSL/whole-program-llvm but got the same results.

The following is when compiling Sqlite3:

```
u@x1 ~/D/g/s/g/d/t/s/sqlite-amalgamation-3250200> export LLVM_COMPILER=clang
u@x1 ~/D/g/s/g/d/t/s/sqlite-amalgamation-3250200> wllvm -o foo shell.c sqlite3.c -lpthread -ldl
objcopy: stxpQkCY: failed to find link section for section 17
objcopy: stxpQkCY: failed to find link section for section 17
objcopy: stpb7U3E: failed to find link section for section 19
objcopy: stpb7U3E: failed to find link section for section 19
u@x1 ~/D/g/s/g/d/t/s/sqlite-amalgamation-3250200> extract-bc foo 
u@x1 ~/D/g/s/g/d/t/s/sqlite-amalgamation-3250200> du -hs foo.bc
2.0M	foo.bc
```

**Note** however that extract-bc works just fine.

Potentially it is due to the objcopy version.

```
u@x1 ~/D/g/s/g/d/t/s/sqlite-amalgamation-3250200> objcopy --version
GNU objcopy (GNU Binutils) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by mewmew** [comment]
> One last comment (don't take this as a insult) but did you try and build without the
CC=wllvm and use CC=clang instead?

No `objcopy` warnings are output when using `CC=clang` instead of `CC=wllvm` in https://github.com/decomp/testdata/blob/master/coreutils/Makefile#L41

```
 CC       src/split.o
  CCLD     src/split
  CC       src/stat.o
  CCLD     src/stat
  CC       src/sum.o
  CCLD     src/sum
  CC       src/sync.o
  CCLD     src/sync
  CC       src/tac.o
```

Similarly, using Clang directly when compiling Sqlite3 produces no `objcopy` warnings.

```
u@x1 ~/D/g/s/g/d/t/s/sqlite-amalgamation-3250200> clang -o foo shell.c sqlite3.c -lpthread -ldl
```

Also, no worries. I don't take offense but rather feel glad you are helping out! Also, one should always try to troubleshoot by removing likely causes one at the time; just as you pointed out.

Cheers,
Robin

**Comment by ianamason** [comment]
OK so let me see if I can replicate it with the version of objcopy that you are using.

**Comment by ianamason** [comment]
OK so I can reproduce it. Not with clang 5.0 and objcopy 2.31.1 but with 
clang 7.0 and objcopy 2.31.1.  Will take a look in more detail why later (probably tomorrow).

**Comment by ianamason** [comment]
OK so I can reproduce it. Not with clang 5.0 and objcopy 2.31.1 but with 
clang 7.0 and objcopy 2.31.1.  Will take a look in more detail why later (probably tomorrow).

**Comment by ianamason** [comment]
Well it appears to be some sort of tension between `clang-7` and `objcopy-2.31.1` that seems to have no effect on the functionality of `wllvm`.  We use `objcopy` to embed the path of the bitcode into the object file. Here yadayada is a file that contains the string `this_is_not_a_love_song` and working inside the `sqlite-amalgamation-3250200` directory:

```
$ /usr/bin/clang-5.0 -c shell.c
$ objcopy --add-section .llvm_bc=yadayada shell.o
$ grep this_is_not_a_love_song shell.o
Binary file shell.o matches
$ /usr/bin/clang-7 -c shell.c
$ objcopy --add-section .llvm_bc=yadayada shell.o
objcopy: stLfFRud: failed to find link section for section 15
objcopy: stLfFRud: failed to find link section for section 15
$ grep this_is_not_a_love_song shell.o
Binary file shell.o matches

```
Not sure what a link section is. The two object files look to have the same sections. @BrunoDutertre 
you got any ideas?

**Comment by ianamason** [comment]
Actually `clang-7` seems to have added a new section called `.llvm_addrsig` which could be the source of the problem.

**Comment by ianamason** [comment]
Indeed  it does seem to be the culprit:
```
$ /usr/bin/clang-7 -c shell.c
$ objcopy --remove-section .llvm_addrsig shell.o
$ objcopy --add-section .llvm_bc=yadayada shell.o
$ grep this_is_not_a_love_song shell.o
Binary file shell.o matches
```

**Comment by ianamason** [comment]
@mewmew  you are welcome (encouraged) to file a bug against binutils.  I will close this issue in the near future.

**Comment by mewmew** [comment]
Done https://sourceware.org/bugzilla/show_bug.cgi?id=23788
