### ISSUE TITLE
Generating bitcode for ARM (cross compile) 

### ISSUE THREAD

**Issue by jiwonjoung** [travitch/whole-program-llvm#77]
Is it possible to generate bitcode for a cross  platform target using wllvm?  
Perhaps something l like passing a CFLAGS argument specifying -march and -target and a path to ARM compatible LLVM tools? 

Has anyone tried this?

**Comment by ianamason** [comment]
Ha!  Yes at least one other person is doing this sort of thing. @mayanez  has a pull request that
is currently open (and just waiting for some yada yada). You could take a look at that. Or just stay tuned.  Seems like it should be no problem, after all you can cross compile with clang, and I guess you can use llvm tools is a similar fashion.

**Comment by ianamason** [comment]
Can I close this @jiwonjoung ?
