### ISSUE TITLE
Build linux kernel 5.X to LLVM IR

### ISSUE THREAD

**Issue by bsauce** [travitch/whole-program-llvm#79]
For now, Linux kernel has been updated to 5.X. I want to compile whole 5.0 kernel to bitcode file. How could I achieve this by using WLLVM? Is there any advice? Thanks for your advice.

**Comment by ianamason** [comment]
Have you looked over [here](https://github.com/SRI-CSL/kernel-specialization.git.)

Not sure if it carries over to the 5.X but it might give you ideas.

**Comment by bsauce** [comment]
I think it helps a lot. Thanks for your advice.
