### ISSUE TITLE
"executable" in file path

### ISSUE THREAD

**Issue by missimer** [travitch/whole-program-llvm#82]
The logic in `FileType::getFileType` does not work if certain keywords are in the file path.  For example I have a directory named "executables" and therefore `getFileType` fails because it picks in "executable" from the path and not the file type information returned by `file`.  A simple fix is to strip away the file path from the output.  I have a one line fix here: https://github.com/missimer/whole-program-llvm/commit/1ac66595af31b1d5ab45f069e8bbfd6444c64122 that I can turn into a pull request or you can just copy the fix.

To reproduce bug:
  Try to compile with wllvm in a directory called "executable"

**Comment by ianamason** [comment]
Ha!  Sure make a pull request. That way you get credit, and go to heaven...

**Comment by missimer** [comment]
fixed in: https://github.com/travitch/whole-program-llvm/pull/83
