### ISSUE TITLE
Cannot handle clang extensions *.c.o

### ISSUE THREAD

**Issue by jojapoppa** [travitch/whole-program-llvm#86]
When using clang object code produced has the extension compiledcode.c.o

However, this file extension is unknown to whole-program-llvm and it fails.

**Comment by ianamason** [comment]
Where does it fail? 
On my system (where hw.c.c is hello world), I can 
```
wllvm hw.c  -c -o hw.c.o
wllvm hw.c.o -o hw.c.exe
```

without a hitch, and I see `.hw.c.o.bc`. 
I can also conflate the two steps via:
```
 wllvm hw.c.c -o hw.c.exe
```
and get similar results (except now, I also get a `.hw.c.o` file)

So can you be more specific?

**Comment by ianamason** [comment]
Just in case you missed my response @jojapoppa I am tagging you this time.

**Comment by jojapoppa** [comment]
Hello Ian,

I created an Issue in github with the error message that I'm getting... I appear to be getting a completed build.
However on extract-bc there are 6 path missing, that are sort of mentioned in the file Ians_notes.

https://github.com/SRI-CSL/musllvm/issues/3

Thank you for the wonderful work.. It's really been fascinating to work with this.  Nice work!

Joja Poppa

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ianamason** [comment]
OK  thanks @jojapoppa I will go over and take a look in the next few days.
