### ISSUE TITLE
what does ${HOME}/wllvm.bin refer to?

### ISSUE THREAD

**Issue by zhanggenex** [travitch/whole-program-llvm#87]
Building freebsd with wllvm in https://github.com/travitch/whole-program-llvm/blob/master/doc/tutorial-freeBSD.md, I am confused what **${HOME}/wllvm.bin** in Makefile.inc1 refers to in Step 5.

And I get the error **could not find ".llvm_bc" elf section in** when extracting the elf file. SO I guess I need to figure out this ${HOME}/wllvm.bin.

Thanks

**Comment by ianamason** [comment]
I an guessing, because those instructions are quite old, but probably the directory where your
wllvm and friends are located.
