### ISSUE TITLE
extract-bc fail to execute, no idea why?

### ISSUE THREAD

**Issue by luosichengx** [travitch/whole-program-llvm#89]
Hi,
I am following the KLEE tutorial to run example project at [,](http://klee.github.io/tutorials/testing-coreutils/) tried to use wllvm to extract bitcode for GNU Coreutils. I work on KLEE's docker image. My step is as follow:
```mkdir obj-llvm
cd obj-llvm
CC=wllvm ../configure --disable-nls CFLAGS="-g -O1 -Xclang -disable-llvm-passes -D__NO_STRING_INLINES  -D_FORTIFY_SOURCE=0 -U__OPTIMIZE__"
... verify that configure worked ...
make
make -C src arch hostname
cd src
find . -executable -type f | xargs -I '{}' extract-bc '{}'
```
but i get the outputs like this:
`ERROR:WLLVM Failed to execute: ['file', '/home/klee/coreutils-6.10/obj-llvm/src/chmod']`
any idea why,thanks.

**Comment by ianamason** [comment]
The docker image is missing the “file” utility.

**Comment by luosichengx** [comment]
thanks for answering the question, i got success but is there any chance you're going to write a more detailed instruction since the error message seem to be a little ambiguous for me.

**Comment by ianamason** [comment]
I asked the klee folk to fix their docker image.

**Comment by luosichengx** [comment]
that would also be okey,thanks.

**Comment by plusultra555** [comment]
I met the same issue.Could you tell me how you got success?

**Comment by ianamason** [comment]
There is a Unix utility called file. 

file foo

will tell you what sort of file foo is. 

You need to make sure it is installed. 

Off hand my guess would be

sudo apt-get install file
