### ISSUE TITLE
extract-bc doesn't create .bc file

### ISSUE THREAD

**Issue by manggoguy** [travitch/whole-program-llvm#90]
I compiled a program using wllvm.
Using extract-bc to create .bc file, but it doesn't work.
It doesn't show error message.

Any have idea this problem?

**Comment by ianamason** [comment]
Not without more details. What does the sanity checker say?

**Comment by manggoguy** [comment]
I resolved this problem. I used python2 and it doesn't works.
It works using python3.

**Comment by ianamason** [comment]
Should work with either. Can you show me it not working for python 2?
