### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by manggoguy** [travitch/whole-program-llvm#91]
I have a configure 
 
the config.log is: 
129 configure:3487: checking whether the C compiler works
130 configure:3509: wllvm    conftest.c  >&5
131 Failed to import the site module
132 Traceback (most recent call last):
133   File "/usr/lib/python3.6/site.py", line 570, in <module>
134     main()
135   File "/usr/lib/python3.6/site.py", line 557, in main
136     known_paths = addsitepackages(known_paths)
137   File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
138     addsitedir(sitedir, known_paths)
139   File "/usr/lib/python3.6/site.py", line 213, in addsitedir
140     addpackage(sitedir, name, known_paths)
141   File "/usr/lib/python3.6/site.py", line 169, in addpackage
142     for n, line in enumerate(f):
143   File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
144     return codecs.ascii_decode(input, self.errors)[0]
144     return codecs.ascii_decode(input, self.errors)[0]
145 UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 10: ordinal not in range(128)
146 configure:3513: $? = 1
147 configure:3551: result: no
148 configure: failed program was:
149 | /* confdefs.h */
150 | #define PACKAGE_NAME "Body Tracking Benchmark"
151 | #define PACKAGE_TARNAME "body-tracking-benchmark"
152 | #define PACKAGE_VERSION "1.0"
153 | #define PACKAGE_STRING "Body Tracking Benchmark 1.0"
154 | #define PACKAGE_BUGREPORT "cbienia@cs.princeton.edu"
155 | #define PACKAGE_URL ""
156 | #define PACKAGE "body-tracking-benchmark"
157 | #define VERSION "1.0"
158 | /* end confdefs.h.  */
159 |
160 | int
161 | main ()
162 | {
163 |
164 |   ;
165 |   return 0;
166 | }

My input is CC=wllvm CXX=wllvm++ ./configure . 
I used "WLLVM_CONFIGURE_ONLY" but it does not work like above error.

**Comment by ianamason** [comment]
Are you telling me that you did
```
CC=wllvm CXX=wllvm++ ./configure
```
or 
```
WLLVM_CONFIGURE_ONLY=1 CC=wllvm CXX=wllvm++ ./configure
```

Also I cannot really help if you do not tell me enough to duplicate the problem.

**Comment by manggoguy** [comment]
I use both, but it doesn't work.
The error message is
checking whether the C compiler works... no
configure: error: in `/home/mok/바탕화면/parsec-modified/pkgs/apps/httpd-2.4.41':
configure: error: C compiler cannot create executables
this is a more config.log 

 79 configure:5316: checking for C compiler version
 80 configure:5325: wllvm --version >&5
 81 Failed to import the site module
 82 Traceback (most recent call last):
 83   File "/usr/lib/python3.6/site.py", line 570, in <module>
 84     main()
 85   File "/usr/lib/python3.6/site.py", line 557, in main
 86     known_paths = addsitepackages(known_paths)
 87   File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
 88     addsitedir(sitedir, known_paths)
 89   File "/usr/lib/python3.6/site.py", line 213, in addsitedir
 90     addpackage(sitedir, name, known_paths)
 91 ... rest of stderr output deleted ...
 92 configure:5336: $? = 1
94 Failed to import the site module
 95 Traceback (most recent call last):
 96   File "/usr/lib/python3.6/site.py", line 570, in <module>
 97     main()
 98   File "/usr/lib/python3.6/site.py", line 557, in main
 99     known_paths = addsitepackages(known_paths)
100   File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
101     addsitedir(sitedir, known_paths)
102   File "/usr/lib/python3.6/site.py", line 213, in addsitedir
103     addpackage(sitedir, name, known_paths)
104 ... rest of stderr output deleted ...
105 configure:5336: $? = 1
106 configure:5325: wllvm -V >&5
107 Failed to import the site module
108 Traceback (most recent call last):
109   File "/usr/lib/python3.6/site.py", line 570, in <module>
110     main()
111   File "/usr/lib/python3.6/site.py", line 557, in main
112     known_paths = addsitepackages(known_paths)
113   File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
114     addsitedir(sitedir, known_paths)
115   File "/usr/lib/python3.6/site.py", line 213, in addsitedir
116     addpackage(sitedir, name, known_paths)
117 ... rest of stderr output deleted ...
118 configure:5336: $? = 1
119 configure:5325: wllvm -qversion >&5
120 Failed to import the site module
121 Traceback (most recent call last):
122   File "/usr/lib/python3.6/site.py", line 570, in <module>
123     main()
124   File "/usr/lib/python3.6/site.py", line 557, in main
125     known_paths = addsitepackages(known_paths)
126   File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
127     addsitedir(sitedir, known_paths)
128   File "/usr/lib/python3.6/site.py", line 213, in addsitedir
129     addpackage(sitedir, name, known_paths)

wllvm-sanity-checker print 
"
wllvm version: 1.2.6
wllvm released: June 18 2019

Logging output to standard error.
Logging level not set, defaulting to WARNING


We are using clang.

The C compiler clang is:

	b''b'clang version 4.0.0 (tags/RELEASE_400/final)\nTarget: x86_64-unknown-linux-gnu\nThread model: posix\nInstalledDir: /usr/local/bin\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.5.0\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7.4.0\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8\nSelected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0\nCandidate multilib: .;@m64\nCandidate multilib: 32;@m32\nCandidate multilib: x32;@mx32\nSelected multilib: .;@m64\n'

The C++ compiler clang++ is:

	b''b'clang version 4.0.0 (tags/RELEASE_400/final)\nTarget: x86_64-unknown-linux-gnu\nThread model: posix\nInstalledDir: /usr/local/bin\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.5.0\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7.4.0\nFound candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0\nFound candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8\nSelected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0\nCandidate multilib: .;@m64\nCandidate multilib: 32;@m32\nCandidate multilib: x32;@mx32\nSelected multilib: .;@m64\n'

The bitcode linker llvm-link is:

	b'LLVM (http://llvm.org/):\n  LLVM version 4.0.0\n  DEBUG build with assertions.\n  Default target: x86_64-unknown-linux-gnu\n  Host CPU: skylake-avx512\n'b''

The bitcode archiver llvm-ar is:

	b'LLVM (http://llvm.org/):\n  LLVM version 4.0.0\n  DEBUG build with assertions.\n  Default target: x86_64-unknown-linux-gnu\n  Host CPU: skylake-avx512\n'b''

Not using a bitcode store. "

**Comment by ianamason** [comment]
The sanity-checker output looks all wrong. 

* What does 
```
wllvm --version
```
output.

* Does the source configure out of the box:
```
./configure
```

**Comment by manggoguy** [comment]
It's a my python problem. 

when site.py opens module, it occurs encoding problem like this.
<_io.TextIOWrapper name='/usr/local/lib/python3.6/dist-packages/easy-install.pth' mode='r' encoding='ANSI_X3.4-1968'>

If it is nomal execution, encoding is 'UTF-8'. 
So I edit site.py. 
In 165 line, f = open(fullname, "r") -->f = open(fullname, "r", encoding='UTF-8')

But I don't know why it occurs executing ./configure. 
I execute only wllvm, it is normal execution.

**Comment by manggoguy** [comment]
wllvm --version 
print clang version normally.

**Comment by ianamason** [comment]
Bizarre. Why not give the python version the flick? We have a much faster
version written in go. It is a drop in replacement. It is [here](https://github.com/SRI-CSL/gllvm)

**Comment by BrunoDutertre** [comment]
This seems to be a Python issue unrelated to wllvm.

Some kind of bug In @manggoguy's python install:

https://stackoverflow.com/questions/21446220/linux-weird-python-output

**Comment by ianamason** [comment]
I agree @BrunoDutertre, which is why I suggested he use gllvm instead.
