### ISSUE TITLE
small suggestion here

### ISSUE THREAD

**Issue by DoubleClass** [travitch/whole-program-llvm#93]
https://github.com/travitch/whole-program-llvm/blob/a66eb59e0b863e38eabc1c24130dee4170edb9fd/wllvm/compilers.py#L272

remarkable work bro!
while configuring my wllvm, I get the invalid compiler err msg, after a whole bunch of searching, I found your source code here.
In user's view the String method is really not satisfying, cause when we have new versions of
clang like clang-6.0，I have to link it to another name "clang" to match your string, and if haven't found your source code, I could still stuck in this "invalid compiler" err msg.
So maybe add a few more options like more strings "clang-6.0", "clang-5.0", or consider using the path instead of matching a string.
Thanks

**Comment by Youggls** [comment]
I just have the same problem, it really bothers me a long time. Plz fix it.

**Comment by ianamason** [comment]
Read the `README.md` more carefully. Pay attention to things like `LLVM_CC_NAME`.

**Comment by Youggls** [comment]
Thx for your explanation.

**Comment by DoubleClass** [comment]
Appologize for my rudeness.
The LLVM_CC_NAME truly worked.

**Comment by ianamason** [comment]
Usually it is not needed. Most installs of llvm that use a version suffix also put non-suffixed versions in an directory like

```
.../llvm-version/bin
```
