### ISSUE TITLE
How to use wllvm without "-c" when building KLEE tutorial?

### ISSUE THREAD

**Issue by LebronX** [travitch/whole-program-llvm#94]
Hi there,

I am now playing around KLEE and try to use wllvm to build bitcode file in the first tutorial (http://klee.github.io/tutorials/testing-function/). But it always complain "undefined reference to 'klee_make_symbolic'" even I give all the dependency(those .a file) of KLEE to wllvm. When I add "-c" to wllvm, things become normal and it can successfully compile. However, I would like to use wllvm without "-c". Does anybody know how use wllvm without "-c" to a single c file and why the situation above will happen?

Thanks!

**Comment by ianamason** [comment]
I don't see `wllvm` mentioned anywhere in that tutorial. So I am not sure why you are trying to use it.  `wllvm` is a tool one uses to build bitcode for realistic projects. 

In the tutorial you need to make the bitcode for `get_sign` which is not an executable but a 
library routine. That is why you would use the `-c` flag.
