### ISSUE TITLE
 “.llvm_bc” ELF section 

### ISSUE THREAD

**Issue by XrazYang** [travitch/whole-program-llvm#98]
When executing "extract-bc main", an error was encountered：
WARNING： Could not find “.llvm_bc” ELF section in " ' ,so skipping this entry.
Hope to get your answer，Thanks。

**Comment by ianamason** [comment]
It means that the object file in question probably wasn't compiled using wllvm. 
Is there any ASM around?
Go any more details?
Kinda hard to see from a million miles away.

**Comment by XrazYang** [comment]
thank you for your reply.
First: Create a new project with clion：
CmakeLists.txt: 
cmake_minimum_required(VERSION 3.10)
project(untitled C)
set(CMAKE_C_STANDARD 99)
add_executable(untitled main.c)
main.c:
#include <stdio.h>
int main() {
    printf("Hello, World!\n");
    return 0;
}

Second: Execute the following command：
#wllvm 
export LLVM_COMPILER=clang
export WLLVM_OUPUT=DEBUG
#cmake
export CC=/usr/local/bin/wllvm
export CXX=/usr/local/bin/wllvm++
#cmake 
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .  #cmake 生成编译数据库
#wllvm make
CC=wllvm CXX=wllvm++ make
extract-bc untitled
It can be executed normally on ubuntu 18.04, but it cannot be executed on Ubuntu 16.04, an error is reported：
Hope to receive your reply。Thanks。

**Comment by ianamason** [comment]
Lots of indirection here.

You need to figure out the actual compiler call that is doing the compiling.
My guess is that it isn't wllvm.

**Comment by XrazYang** [comment]
thank you for your reply.
I changed the content of the “CmakeLists.txt”：
cmake_minimum_required(VERSION 3.10)
project(untitled C)
set(CMAKE_C_COMPILER "/usr/local/bin/wllvm")
set(CMAKE_CXX_COMPILER "/usr/local/bin/wllvm++")
set(CMAKE_C_STANDARD 99)
add_executable(untitled main.c)
But there is the same problem. Thanks.

**Comment by ianamason** [comment]
As I said earlier. You need to look at the Makefile that get generated and see what is actually
doing the compiling. This is almost certainly not an issue with wllvm.
